### ISSUE TITLE
serialization, canonicalized values and normalized datasets

### ISSUE THREAD

**Issue by nightpool** [w3c/vc-data-integrity#11]
Hey all, someone in the ActivityPub community was attempting to implement JSON-LD signatures recently, and they came across this issue:

https://socialhub.activitypub.rocks/t/making-sense-of-rsasignature2017/347

> None of the specs say anything about the ordering of the RDF quads. The JSON-LD spec doesn’t mention it but the test suite page tells you that you need to compare them using “RDF isomorphism” which, if I understood all that type theory mumbo-jumbo correctly (gosh, it feels like making a Telegram client from scratch again), means you have to disregard the order which is what I do for my tests. The URDNA2015 spec doesn’t say anything about the ordering either. But For each quad, quad, in input dataset: as the last step, even though you sort things internally, kinda implies that you’re supposed to keep the order of the original dataset. The test suite page doesn’t say anything about ordering either.

As I understand the specs in question, URDNA2015's Normalization Algorithm returns a normalized **dataset**, which elides the problem of serialization. However, the ld-signatures algorithm seems to be expecting URDNA2015 to return a canonicalized **value**, which is a **serialization** of a normalized dataset, presumably specifying ordering and things like that.

Here's a quote from the rdf-normalization spec discussing this very issue:

> This specification defines a normalized dataset to include stable identifiers for blank nodes, but practical uses of this will always generate a canonical serialization of such a dataset

What rules should implementations use to turn URDNA2015's normalized dataset into a canonical serialized value? ruby's rdf-normalize gem uses the following code: 

https://github.com/ruby-rdf/rdf-normalize/blob/develop/lib/rdf/normalize/writer.rb#L56-L63

    statements = RDF::Normalize.new(@repo, @options).
      statements.
      reject(&:variable?).
      map {|s| format_statement(s)}.
      sort.
      each do |line|
        puts line
      end

Does the `.sort` here correspond to any spec?

**Comment by msporny** [comment]
I'm trying to figure out if there is more that we need to do here, @gkellogg or @dlongley?

We do have better algorithms defined in the spec now:

https://w3c.github.io/vc-data-integrity/#algorithms

and specific ones in the cryptosuites that speak to use of RDF canonicalization:

https://w3c.github.io/vc-di-eddsa/#algorithms

... but we also know that the algorithms are still a bit hard to read and piece together.

I'm going to keep this issue open until we feel like we're at feature freeze w/ the algorithms (next couple of months). I expect that we'll also be providing an option to do canonicalization via JSON Canonicalization Scheme (JCS), which might help the Mastodon/fediverse folks out with an easier to implement option for signing ActivityPub messages.

**Comment by gkellogg** [comment]
Specifying a canonical serialization of a normalized dataset, while trivial, is still an open item in RDF RCH, as is a mechanism for selective disclosure. It still isn’t decided if it goes in the rdf-canon spec or a new spec.

it seems to me that the pace of the RCH WG is a bit slow, and other issues have been prioritized in bi-weekly discussions. For a straight serialization of a normalized dataset, additional text would be easy enough; just waiting on direction from the WG.

**Comment by msporny** [comment]
> I expect that we'll also be providing an option to do canonicalization via JSON Canonicalization Scheme (JCS), which might help the Mastodon/fediverse folks out with an easier to implement option for signing ActivityPub messages.

This option exists now for the Mastodon/fediverse folks... both for EdDSA and ECDSA:

* https://www.w3.org/TR/vc-di-ecdsa/#jcs-ecdsa-2019
* https://www.w3.org/TR/vc-di-eddsa/#jcs-eddsa-2022

We have multiple fediverse implementers that are looking at implementing jcs-eddsa-2022 (which doesn't use RDF Dataset Canonicalization, and uses JSON Canonicalization Scheme instead).

The RDF Dataset Canonicalization spec now also includes the language described in this issue as well:

https://w3c.github.io/rdf-canon/spec/

So, I believe we've done what we can here. I'm going to mark this as pending close, and the issue will be closed in 7 days unless someone disagrees that we've addressed the issue in the current set of specifications.
