### ISSUE TITLE
Expand use of `previousProof` to allow an array, define in security vocabulary

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-integrity#120]
@lemoustachiste wrote in https://github.com/w3c/vc-data-integrity/issues/26#issuecomment-1640168246:
> I think it might be easier to specify an array of previous proofs that were signed, rather than multiplying signatures on a 1 to 1 basis.
>  I couldn't find the vocabulary for `previousProof`

**Comment by msporny** [comment]
> @lemoustachiste wrote:
> I think it might be easier to specify an array of previous proofs that were signed, rather than multiplying signatures on a 1 to 1 basis.

Ok, I agree, we'll make the change in the spec.

> I couldn't find the vocabulary for `previousProof`

Yes, it's a relatively new addition and we were waiting for community feedback before we set it in stone.

People seem to be supportive of the direction, so now is probably the right time to add it to the security context. We'll do that in a future PR.

**Comment by dlongley** [comment]
@msporny,

I think it's ok to do. I do think we should give guidance in the verification algorithms around throwing errors when cycles are detected. For example, it sounds like it's possible for someone to add two proofs that reference each other in `previousProof`. So implementers should just keep track of whether they are able to go from tail to head without cycling when doing verification. I don't think this should get any more complex (other than iterating over a set of `previousProof` values instead of following just one) with multiple values.

**Comment by Wind4Greg** [comment]
I've put together some text to expand  the definition of `previousProof` (to allow an array in addition to a string) and the algorithms (including cycle detection), but was going to wait until the previous PR https://github.com/w3c/vc-data-integrity/pull/121 finishes the approval process. Let me know if you think I should proceed otherwise.

**Comment by iherman** [comment]
@msporny just to be precise: the proposal is really an _array_, i.e., a _sorted_ collection of terms. I.e., when added to the vocabulary, the range must be, in RDF terms, a List. Or, more exactly (I presume) either a single value or a list thereof.

If the order is not significant, the vocabulary is also fairly different...

**Comment by msporny** [comment]
> @msporny just to be precise: the proposal is really an _array_, i.e., a _sorted_ collection of terms. I.e., when added to the vocabulary, the range must be, in RDF terms, a List. Or, more exactly (I presume) either a single value or a list thereof.
> 
> If the order is not significant, the vocabulary is also fairly different...

IIUC, the order is not significant... so, I don't think we should use RDF List semantics here. `previousProof` is an unordered set (from a data modelling perspective).

**Comment by iherman** [comment]
> > @msporny just to be precise: the proposal is really an _array_, i.e., a _sorted_ collection of terms. I.e., when added to the vocabulary, the range must be, in RDF terms, a List. Or, more exactly (I presume) either a single value or a list thereof.
> > If the order is not significant, the vocabulary is also fairly different...
> 
> IIUC, the order is not significant... so, I don't think we should use RDF List semantics here. `previousProof` is an unordered set (from a data modelling perspective).

As the maintainer of the vocabulary, I certainly prefer not to use lists 😀... But we should then be careful how we formulate this in the spec. "Array" _usually_ means ordered for most people.

**Comment by msporny** [comment]
> As the maintainer of the vocabulary, I certainly prefer not to use lists 😀... But we should then be careful how we formulate this in the spec. "Array" _usually_ means ordered for most people.

Yes, agreed. The way we deal with this in the core data model is using this sort of language: 

> The value of the X property MUST be one or more URLs. If more than one URL is provided, the URLs MUST be interpreted as an unordered set.

One example of this is here:

https://w3c.github.io/vc-data-model/#types

We could probably take the same approach with this property.

**Comment by TallTed** [comment]
> `previousProof` is an unordered set (from a data modelling perspective).

How does one test all proofs in reverse, if the set is unordered?

(People have been talking about testing such multiple proofs in original order of application, which doesn't make sense to me yet, but it seems to me that that still calls for an ordered set.)

I'm not a crypto wizard, so I may well be misunderstanding how something works. Explanation which clarifies it for me will likely also clarify it for other readers. :-)

**Comment by dlongley** [comment]
> How does one test all proofs in reverse, if the set is unordered?

The "order" there (implicit in the use of the word "reverse") refers more to the level in a dependency tree and would be resolved by directional links, not by the membership in a set (and its lack of order).

For example, proof A would have signed "on top of" proof B -- as A will have referenced B (and *not* vice versa) and therefore "depends" on it. If proof A also references C, such that A has a `previousProof` set containing both "dependencies" B and C, this not a problem for "testing all proofs in reverse", it's just that both B and C (in whatever order) must both verify if A is to also verify.

It would be an error if B (or any of the proofs further up the tree it references) references A. But this is a cyclical dependency problem -- which was mentioned above; this error can be detected and rejected.

For example, `previousProof` can be thought of as representing the top row in these trees; the order there doesn't matter for proof verification:

```
C - B
 \ /
  A
```

```
B - C
 \ /
  A
```

**Comment by Wind4Greg** [comment]
To say it another way, we have an unordered list of signatures/proofs. The dependency relationships (if any) between signatures/proofs is given by the `previousProof` attribute associated with a given signature/proof.

Note that cycle detection is fairly well studied: [wikipedia: Cycle Detection](https://en.wikipedia.org/wiki/Cycle_detection), [Wikipedia: graph theory cycle detection](https://en.wikipedia.org/wiki/Cycle_(graph_theory)#Cycle_detection). In the new text I'll have a PR on soon I'll just give on mechanism for doing this, keeping track of visited signatures/proofs ("nodes").

**Comment by iherman** [comment]
> In the new text I'll have a PR on soon I'll just give on mechanism for doing this, keeping track of visited signatures/proofs ("nodes").

Thanks in advance, @Wind4Greg. It is essential to have this described in the spec.

**Comment by msporny** [comment]
PR #145 has been raised to address this issue. Once that PR is merged, this issue will be closed.

**Comment by msporny** [comment]
PR #145 has been merged, closing.
