### ISSUE TITLE
Missing term definitions in the spec

### ISSUE THREAD

**Issue by iherman** [w3c/vc-data-integrity#129]
As reported in #127, the current vocabulary includes three terms that do not have a formal specification in the DI spec, namely: `proof`, `nonce`, and `revoked`. These entries must be present.

Note that there is a PR (#122) that may take care of the `nonce` case.

**Comment by iherman** [comment]
`nonce` is being taken care of by #142

**Comment by msporny** [comment]
`proof` is being taken care of in PR #153.

**Comment by msporny** [comment]
`revoked` is being taken care of in PR #154.

**Comment by msporny** [comment]
PRs #142, #153, and #154 have been raised to address this issue. Once those PRs are merged, this issue will be closed.

**Comment by msporny** [comment]
PRs #142, #153, and #154 have been merged, closing.
