### ISSUE TITLE
[Terminology] Definition of a linked data document is not discernable

### ISSUE THREAD

**Issue by mwherman2000** [w3c/vc-data-integrity#13]
In https://w3c-dvcg.github.io/ld-signatures/#terminology, it states...

> linked data document
> A document comprised of Linked Data.

...but there is no definition for Linked Data.  The above definition is not discernable. e.g. scenarios like Issue https://github.com/w3c-dvcg/ld-signatures/issues/22

Need to add a definition in the Terminology section for Linked Data.

**Comment by msporny** [comment]
There is now a deeper explanation of linked data and its relationship to the specification here:

https://w3c.github.io/vc-data-integrity/#relationship-to-linked-data

Closing.
