### ISSUE TITLE
Add diagrams and test vectors for `previousProof`

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-integrity#132]
In https://github.com/w3c/vc-data-integrity/pull/121#issuecomment-1642528752, @OR13 wrote:
> I would want to see a spanning visual example of how complicated this [Proof Chains and Proof Sets] can get, and I would want to see some tests cases for implementer to base their implementations on.

**Comment by Wind4Greg** [comment]
Hmm, where to put this? In data integrity or in a specific cryptosuite or in some kind of implementers guide? I imagine it will be about as long as one of the complete test vector examples in EdDSA or ECDSA, but different, i.e., we will want to show the building up of a proof chain in a couple steps. Will we also want to demonstrate (probably a separate example) of the case of `previousProof` as an unordered list.

**Comment by msporny** [comment]
> Hmm, where to put this? In data integrity or in a specific cryptosuite or in some kind of implementers guide?

Yeah, the best place is probably an implementers guide, but we don't have that document. It probably shouldn't go in a specific cryptosuite because the proof set / chain stuff is a generalized mechanism that any cryptosuite can use. So, the best place for this is probably the base data integrity specification.

> I imagine it will be about as long as one of the complete test vector examples in EdDSA or ECDSA, but different, i.e., we will want to show the building up of a proof chain in a couple steps. Will we also want to demonstrate (probably a separate example) of the case of `previousProof` as an unordered list.

Yes, agreed. That said, this is all editorial/documentation stuff, so can wait until after we're in CR.

**Comment by msporny** [comment]
The specification now contains a section detailing how proof sets and proof chains work here:

https://w3c.github.io/vc-data-integrity/#understanding-proof-sets-and-proof-chains

There are also tests for each cryptosuite that check for the presence of (and presumably the validity of) `previousProof` here (@aljones15 , please confirm that the test suites check the validity of a proof chain and a proof set):

https://github.com/w3c-ccg/data-integrity-test-suite-assertion/blob/e6ecde60b53e37a1fc46333b5840896ffb17cd82/suites/create.js#L212-L220

@Wind4Greg you mentioned that we have test vectors for proof sets and chains, but I couldn't find them. Could you please link to them in this issue?

The Editors have discussed the importance of having "a spanning visual example of how complicated this [Proof Chains and Proof Sets] can get" and have decided that such an example wouldn't be useful. Instead, we've raised issue #275 to advise implementers to put in reasonable limits for algorithms (which is obvious, implementers do that naturally, but due to this issue, we have decided to be explicit about an implementers responsibility to provide reasonable defaults.

**Comment by Wind4Greg** [comment]
For the proof chain/set test vectors see the EdDSA spec: https://w3c.github.io/vc-di-eddsa/#proof-sets-and-chains. There are three subsections.

**Comment by msporny** [comment]
Thanks @Wind4Greg, with that, I'm closing this issue as addressed.
