### ISSUE TITLE
Add table for all error conditions

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-integrity#136]
In https://github.com/w3c/vc-data-integrity/issues/66#issuecomment-1300669373, @mprorock wrote:
> should we consider using [RFC 7807](https://www.rfc-editor.org/rfc/rfc7807) for error responses?

The algorithms in the data integrity specification throw errors when they detect invalid inputs. At times, it would be helpful to expose these errors over HTTP APIs. @mprorock has suggested that we use RFC 7807 for this purpose. This is a tracking issue to discuss the topic.

**Comment by msporny** [comment]
I think it would be a good idea to provide enough documentation for implementers to follow RFC 7807 if they wanted to. We can't mandate that implementations use RFC 7807 (because some implementations might be in C/C++ and never expose their details over HTTP). What we can do, however, is create a non-normative table for error conditions that choose to use RFC 7807. We might even provide error code numbers, which would be returned by software libraries in non-HTTP environments.

This could be added to the specification in a appendix containing a table of error codes and their human-readable descriptions. An example of such an error could look like this:

```
{
  "type": "https://w3id.org/security#MalformedProofError",
  "code": -16,
  "title": "Missing `type` field in `proof`.",
  "detail": "The `proof.type` value is required and was not set.",
  "proof": { ... PROVIDED_PROOF_VALUE_GOES_HERE ... }
}
```

**Comment by msporny** [comment]
> https://w3id.org/security#MalformedProofError

@iherman, should we put the error definitions in the security vocabulary, or somewhere else? I think I'd prefer that we put them in the security vocabulary. RFC 7807 doesn't require that the URL be an RDF class/property, but there is a fairly easy/powerful overlap to make it link to a Linked Data vocabulary. 

The other option is that we link directly to the table in the specification, but we'd want the fragment identifiers to resolve between future versions of the specification, which is not guaranteed if we put it in a versioned specification. 

It feels like the best place for these values is the vocabulary document, which would then point to the latest specification via `defined_by`. Thoughts?

**Comment by iherman** [comment]
I am not convinced the security vocabulary is really a good place for this. What does it have to do with Linked Data? How does it relate to the other terms?

***If*** it is to go there, I think the correct way is to define a Class for errors, and, e.g., `https://w3id.org/security#MalformedProofError` is an _instance_ (not a class, and not a property). In other words, the vocabulary would look like

```
sec:VCError rdf:type rdf:Class .
sec:MalformedProofError rdf:type sec:VCError;
sec:AnyOtherError rdf:type sec:VCError;
```

This is structurally simple, and it can be done, but the introduction of this `sec:VCError` as a holder for errors (in other environments I would say "Exceptions") seems to be out of the blue. Unless there is a vocabulary out there in Linked Data land that describes run-time errors like that (@pchampin any idea?).

Frankly... having a list in the spec of the exceptions (sorry, errors 😀) is good enough. Every programming environment have a means to handle these, I do not think it helps to interfere with those.

**Comment by msporny** [comment]
> I am not convinced the security vocabulary is really a good place for this. What does it have to do with Linked Data? How does it relate to the other terms?

[RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807) requires that the `type` field uses a URL that is dereferenceable such that implementers can use the URL to look up errors in a specification. It just so happens that RFC7807's usage of `type` overlaps with the way we use `type` in VCs and DI almost completely. Effectively, it is Linked Data (for a looser definition of Linked Data than some in the RDF community might use).

Simultaneously, we're looking for a way to express errors in a standardized way in the VC API: https://github.com/w3c-ccg/vc-api/issues/331

The problem is that if we end up using URLs that look like this:

https://www.w3.org/TR/vc-data-integrity#THE_ERROR_VALUE

Then, when vc-data-integrity-2.0 comes out, we end up possibly losing the anchors (or, we have to remember that we have to preserve the anchors):

https://www.w3.org/TR/vc-data-integrity#THE_ERROR_VALUE

All this to say, this is why https://w3id.org/ exists (so the redirections to the most up to date specification work over time). We expect the vocabulary documents at https://www.w3.org/ns/ to have long-term stability, so I was trying to figure out a way to use those.

> In other words, the vocabulary would look like
> 
> ```
> sec:VCError rdf:type rdf:Class .
> sec:MalformedProofError rdf:type sec:VCError;
> sec:AnyOtherError rdf:type sec:VCError;
> ```

Yes, we could do that. 

> This is structurally simple, and it can be done, but the introduction of this `sec:VCError` as a holder for errors (in other environments I would say "Exceptions") seems to be out of the blue. Unless there is a vocabulary out there in Linked Data land that describes run-time errors like that (@pchampin any idea?).

Some guy put this together over 13 years ago... :P

https://www.w3.org/2010/02/rdfa/wiki/Error_vocabulary

Other than that one, I don't know of any.

> Frankly... having a list in the spec of the exceptions (sorry, errors grinning) is good enough. Every programming environment have a means to handle these, I do not think it helps to interfere with those.

It's the stability of the URLs that I'm concerned about over time. I'm fine w/ the definitions being in the main spec... just, which URLs are we going to use for that. Some options include:

* https://www.w3.org/TR/vc-data-integrity#THE_ERROR_CODE (where we have to make sure that these always resolve to the latest specification and no error codes are removed)
* https://www.w3.org/ns/security/data-integrity#THE_ERROR_CODE (where we create a new document and point back to the specification that defined the code and keep this document up to date over time)
* https://www.w3.org/ns/security#THE_ERROR_CODE (where we re-use the security vocabulary to point back to the specification that defined the code)

Each option has benefits and drawbacks. Thoughts?

**Comment by msporny** [comment]
PR #140 has been raised to address this issue. This issue will be closed once PR #140 is merged.

**Comment by iherman** [comment]
Just for the records, if we go down the route of putting things into the security vocabulary, then

```
sec:VCError rdf:type rdf:Class .
sec:MalformedProofError rdf:type sec:VCError;
sec:AnyOtherError rdf:type sec:VCError;
```

would look, in the yaml definition, as follows

```yaml
class:
    - id: VCError
      label: Error Condition
      comment: A class grouping all error conditions defined by the VC specifications
. . .
individual:
    - id: MalformedProofError
      upper_value: sec:VCError
      label: Malformed Proof Error
      defined_by: https://www.w3.org/TR/vc-data-integrity/#XYZ
    - id: XXXX
      . . .
```

**Comment by iherman** [comment]
> > I am not convinced the security vocabulary is really a good place for this. What does it have to do with Linked Data? How does it relate to the other terms?
> 
> [RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807) requires that the `type` field uses a URL that is dereferenceable such that implementers can use the URL to look up errors in a specification. It just so happens that RFC7807's usage of `type` overlaps with the way we use `type` in VCs and DI almost completely. Effectively, it is Linked Data (for a looser definition of Linked Data than some in the RDF community might use).

If I am not mistaken, RFC 7807 is related to HTTP APIs. I do not believe that is what we are talking about here, at least not exclusively. These errors are, essentially, exceptions raised by the application... But I also realize that there may be similar situations coming up with the VC API.

To be clear: I am not convinced, but I am not fundamentally opposed to use URL-s. If the consensus is to do that, I am happy to go with the flow.

> […]
> 
> All this to say, this is why https://w3id.org/ exists (so the redirections to the most up to date specification work over time). We expect the vocabulary documents at https://www.w3.org/ns/ to have long-term stability, so I was trying to figure out a way to use those.

I do understand that, and *if* we agree to use URLs, then indeed something like `w3id` or `/ns` should be used. And if we are at that point, then I agree that folding it with the security vocabulary makes it simpler.

[…]
 
> > Frankly... having a list in the spec of the exceptions (sorry, errors grinning) is good enough. Every programming environment have a means to handle these, I do not think it helps to interfere with those.
> 
> It's the stability of the URLs that I'm concerned about over time. I'm fine w/ the definitions being in the main spec... just, which URLs are we going to use for that. Some options include:
> 
> * https://www.w3.org/TR/vc-data-integrity#THE_ERROR_CODE (where we have to make sure that these always resolve to the latest specification and no error codes are removed)
> * https://www.w3.org/ns/security/data-integrity#THE_ERROR_CODE (where we create a new document and point back to the specification that defined the code and keep this document up to date over time)
> * https://www.w3.org/ns/security#THE_ERROR_CODE (where we re-use the security vocabulary to point back to the specification that defined the code)

If we put these terms into the security vocabulary, then the situation becomes clear. The URLs would be of the form `https://w3id.org/security#THE_ERROR_CODE` (alongside all the other terms in the vocabulary). See also https://github.com/w3c/vc-data-integrity/issues/136#issuecomment-1657770647.

---

As an aside, we should stop referring to `https://www.w3.org/ns/security`. That URL does not exist and, in my view, it should not, because
    1. The official URL for the vocabulary is, at least at this moment, at `https://w3id.org/security/#`; it has been used that way for many years, and it would invalidate all deployments out there if we decided to move it. As a consequence:
    2. The only reason for `https://www.w3.org/ns/security#` would be to ensure long term stability and that URL would be hidden for users. But that is ***not*** why the `/ns` space is for: it is used for "official" vocabulary URLs. If we are looking for a long terms stability, that is why we have the W3C data space.  
    3. Even if we decided to scrap `w3cid` and we decided to create a new `/ns` URL for the vocabulary, I would prefer to go for `/ns/data-integrity`, which is already in use for the context, and which is bound to the current name of the spec. We should not create a proliferation of namespaces `/ns/security` is way too general for us to grab it on the W3C namespace, it would be inappropriate for us to try to do that.

**Comment by msporny** [comment]
@iherman just some responses for you here:

```
sec:ProcessingError rdf:type rdf:Class .
sec:MalformedProofError rdf:type sec:ProcessingError;
sec:AnyOtherError rdf:type sec:ProcessingError;
```

Then what if we put the security vocabulary here (which is where `https://w3id.org/security` would redirect to)?

```
https://www.w3.org/ns/data-integrity/
```

> If I am not mistaken, RFC 7807 is related to HTTP APIs. I do not believe that is what we are talking about here, at least not exclusively. 

Yes, not exclusively... there is text in the specification now that says: "If you expose an error through an HTTP API, you SHOULD use the error URLs defined in this specification..."

Hope that helps explain the above, I think we're aligned (unless I'm missing a piece of all these puzzle pieces coming together, which I very well might be missing!).

**Comment by msporny** [comment]
PR #140 has been merged, closing.
