### ISSUE TITLE
[EXAMPLE 1] Is Example 1 technically a Linked Data document or just a Simple Document?

### ISSUE THREAD

**Issue by mwherman2000** [w3c/vc-data-integrity#14]
In https://w3c-dvcg.github.io/ld-signatures/#ex-1-a-simple-linked-data-document, it states...

> EXAMPLE 1: A simple Linked Data document
> {
>   "@context": "https://w3id.org/identity/v1",
>   "title": "Hello World!"
> }

Is this technically a Linked Data compliant document?  ...it's impossible to tell from the definition of the linked data document in the Terminology section (see Issue https://github.com/w3c-dvcg/ld-signatures/issues/23)

**Comment by msporny** [comment]
Example 1 has been updated to remove `@context`... it now reads "A simple JSON data document":

https://w3c.github.io/vc-data-integrity/#example-a-simple-json-data-document

Closing.

**Comment by mwherman2000** [comment]
@msporny Are Example 1 (and Example 2) considered to be _credentials that are compliant_ with Verifiable Credential V2 specification?

Reference: https://w3c.github.io/vc-data-integrity/#example-a-simple-json-data-document

**Comment by msporny** [comment]
> @msporny Are Example 1 (and Example 2) considered to be _credentials that are compliant_ with Verifiable Credential V2 specification?

No, and they don't need to be to use the Data Integrity specification.

**Comment by mwherman2000** [comment]
> No, and they don't need to be to use the Data Integrity specification.

Understoood. Just the same, a clarifying comment needs to be added.  Especially given the title of your spec is: 

> Verifiable Credential Data Integrity 1.0
> This specification describes mechanisms for ensuring the authenticity and integrity of _Verifiable Credentials and similar types of constrained digital documents_ using cryptography, especially through the use of digital signatures and related mathematical proofs.

**Comment by msporny** [comment]
> and similar types of constrained digital documents

The examples fall under this category ^^^

What sort of clarifying statement would you like to see in the document?

I'm re-opening this issue now, given that you have requested changes.

**Comment by mwherman2000** [comment]
@msporny When I look at the surrounding text, I feel the explanation would be somewhat convoluted. 
Also, Example 1 doesn't contribute very much to the data integrity discussion.

Recommendation: Remove Example 1 and related text ...or... change/fix the title (e.g. Credential Data Integrity spec) and then position Example 1 as a credential with no credential data integrity features/capabilities. "Level zero" support.

Which of the remaining examples are also not VC2 compliant?

**Comment by msporny** [comment]
PR #105 has been raised to address this issue. This issue will be closed once that PR has been merged.
