### ISSUE TITLE
Examples of the "domain" field in use?

### ISSUE THREAD

**Issue by cwebber** [w3c/vc-data-integrity#15]
It seems to me that the "domain" field is very particular to a particular proofPurpose domain.  It doesn't seem very general to me.

I also exhibit skepticism about having a domain field anyway... blame me spending too much time reading ocap literature:

> "perimeter defense", which is more correctly described as "eggshell defense". It is like an eggshell for the following reason: while an eggshell may seem pretty tough when you tap on it, if you can get a single pinhole anywhere in the surface, you can suck out the entire yoke. -- [E in a Walnut](http://www.skyhunter.com/marcs/ewalnut.html)

**Comment by dmitrizagidulin** [comment]
@cwebber - has your question been addressed, or do you still want to keep this issue open?

**Comment by llorllale** [comment]
@cwebber @dlongley @msporny @dmitrizagidulin 

I arrived here looking to understand the purpose of `domain`. From what I gather, it is effectively a namespace for `challenge`. Would this be a correct interpretation? 

Does the Holder need to understand the `domain` value?

**Comment by dlongley** [comment]
@llorllale,

> I arrived here looking to understand the purpose of domain. From what I gather, it is effectively a namespace for challenge. Would this be a correct interpretation?

Yes, that's one way of interpreting it. A verifier should be expecting a particular `domain` and `challenge` value, both of which help prevent against replay attacks. The `challenge` value is intended to carry a sufficiently large random value to prevent replay at the same location/within the same context. The `domain` value identifies a location or context for which the proof is targeted. Both are signed over when creating a signature proof.

The `holder` doesn't necessarily need to understand the `domain` value, but their software agent should understand `domain` to a "target" for the proof. The data model doesn't get more rigid than this, but protocols can. Some protocols could require a client to ensure that `domain` carries, for example, the value of a particular Web origin -- one that matches the Web origin that the client is interacting with and intends to send a presentation with a proof to.

**Comment by msporny** [comment]
Examples for the domain and challenge field are now included in the spec: https://w3c.github.io/vc-data-integrity/#proofs

These fields are being used in at least the Verifiable Presentation Request specification here:

https://w3c-ccg.github.io/vp-request-spec/#did-authentication

Interoperability on the usage of this property has been provided for multiple issuers (12-ish) and digital wallets (5-ish) in the VCWG during JFF Plugfest 2:

https://docs.google.com/presentation/d/19GmJ3bLMrbVadesnkmsWaaUr-U71Y9Kr775tZvgs-xI/edit#slide=id.g18a979873b4_2_2

Closing given that domain and challenge has been implemented, deployed, and is in use.
