### ISSUE TITLE
Add reference back to VC Data Model Security and Privacy Considerations sections

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-integrity#167]
From the PING's review (https://github.com/w3cping/privacy-request/issues/120):
> It may be worth adding a pointer back to the VC Data model's privacy considerations section here and throughout the various Cryptographic suites since the privacy considerations are often relevant to the various specs.

/cc @kdenhartog

**Comment by msporny** [comment]
PR #173 has been raised to address this issue. This issue will be closed once PR #173 has been merged.

**Comment by bob420-svg** [comment]
Can I help with anything?

**Comment by msporny** [comment]
> Can I help with anything?

Are you a bot? You've added some questionable tagging in a variety of PRs -- can you identify yourself? Your behavior looks like the sort used when Github star farms try to build profiles to raise fake PRs/engagements.

**Comment by msporny** [comment]
PR #173 has been merged, closing.

**Comment by bob420-svg** [comment]
Bro I'm not a bother. I'm the guy with all the iprs. I'm not trying to mess
things up or add more work I just don't know how to use github. I see me
sitting on the side as a member that doesn't contribute as a cheap way out.
I was trying to live up to my word and fix what I messed up and I'm unsure
if I'm doing it right. I'm Daniel Bynum.
