### ISSUE TITLE
Use cases for RsaSignatureAuthentication2018 / authentication suites

### ISSUE THREAD

**Issue by cwebber** [w3c/vc-data-integrity#17]
A recent use case lead us to a document that looked like the following:

```
{
 "@context": "https://w3id.org/veres-one/v1",
 "id": "did:v1:XQyBgxKSYO_hUwNw8okbivbbKG6wEmD-oDdq99Po8Qo",
  ...
  "publicKey": [{
   "id": "did:v1:XQyBgxKSYO_hUwNw8okbivbbKG6wEmD-oDdq99Po8Qo#cap-grant-key",
   "type": "RsaSigningKey2018",
   "owner": "did:v1:XQyBgxKSYO_hUwNw8okbivbbKG6wEmD-oDdq99Po8Qo",
   "publicKeyPem": "-----BEGIN PUBLIC KEY...END PUBLIC KEY-----\r\n"
 }, ...],
  "grantCapability": [{
   // this key can be used to grant capabilities
   "type": "RsaSignatureAuthentication2018",
   "publicKey": "did:v1:XQyBgxKSYO_hUwNw8okbivbbKG6wEmD-oDdq99Po8Qo#cap-grant-key"
 }]
}
```

What's interesting here is that `publicKey` is directly referring to a key, whereas `grantCapability` refers to an "application suite", which itself also refers to a key.  I was confused by this but @msporny clarified that the difference is that the latter is an application suite which, though it has indirection, can also specify various constraints on (as I understand it) both the key it points to, as well as signatures/proofs using that key.  (Do I have this right?)

This might be useful, but I'm not sure... I'm trying to work it out.  Here are some thoughts:

- What are restrictions we might do on keys?  One example is adding a minimum key size for example.
  - Quoting Manu: 'because you may want to have different cryptographic requirements for different applications. For example, I want to make sure that something is a hardware backed key for grantCapability ("RsaHardwareBackedAuthentication2018"), but any software key is fine for invokeCapability ("RsaSignatureAuthentication2018"). Where would you specify those restrictions if you were to just reference a key?'
- What are restrictions we might do on signatures?  (And would it be possible to just put these restriction fields in the key type rather than the algorithm type also?  Why not?)
- Okay, let's think about how such an enforcement of key size or key/material type (hardware etc) would work in practice:
  - `grantCapability` is an application suite type, and specifies that one must have a hardware key of no less than 2048 bits.  `publicKey` can be updated by a capability:
    - Assume it's a capability to update the entire field of `grantCapability`.  Well in that case I can always strip off the hardware key requirement and the minimum keysize requirement and just replace it with different requirements for another key anyway, so we might as well have just had a key rather than the application suite.
    - Assume it's a capability with the caveat to *only* update the `publicKey` field of the `grantCapability`.  Now we're cookin!  This would indeed keep the restrictions on keysize and key type.  (Though this check would always happen at signature verification time, rather than once on setting the key.)
  - Now let's imagine that `grantCapability` actually just has the type of the key rather than an application suite that points at a key.
    - Assume it's a capability to update the entire field of `grantCapability`, sans additional caveats.  In this case this is equivalent to the first application suite case... in both cases, you can swap out to *any* key.  Okay.
    - But can we get the restriction we had previously?  We could... instead of putting a caveat that says "only update the `publicKey` field of `grantCapability`" (which no longer applies anyway) we can add a *different* caveat... one that says that "you can replace the `grantCapability` key, but only if the key you replace it is a hardware key with a minimum of 2048 bit keylength!"  Hey look, we got the same restriction, but one nice thing is that we don't have any additional work to do at each signature check time... we only have to do it once, at a single key-rotation invocation time.

What do you think?

**Comment by msporny** [comment]
No discussion in 4 years on this issue.

In the meantime, the W3C DID WG had a long set of discussions about this topic and came to consensus on sections in DID Core here:

https://www.w3.org/TR/did-core/#verification-methods
https://www.w3.org/TR/did-core/#verification-relationships

Those went out as a W3C REC in July 2022, and the VC Data Integrity work (this spec repo) pulls that language in here:

https://w3c.github.io/vc-data-integrity/#controller-documents

As a result, this issue has been resolved given that spec text exists and has gone out as a W3C REC over the past couple of years. Closing as addressed, please re-open if you feel that we failed to address something in this issue thread via the normative spec text.
