### ISSUE TITLE
Should this suite normatively require integrity checking of the context files?

### ISSUE THREAD

**Issue by kdenhartog** [w3c/vc-data-integrity#179]
There's been a really interesting discussion about the topic in the LDI WG charter here: https://github.com/w3c/lds-wg-charter/issues/83

Based upon that issue, I'm thinking this is the best place to normatively require integrity checking of a context file using a hashlink and if a context is not integrity protected or doesn't validate it MUST fail.

Thoughts? @tplooker @peacekeeper @philarcher @dlongley @msporny @dmitrizagidulin @OR13 

Also I'm going to refrain from posting this on every LDI suite so that we can keep the conversation closely constrained here.

**Comment by dmitrizagidulin** [comment]
@kdenhartog the VC Data Model 2.0 now has a general mechanism to check the integrity of contexts and other related resources: https://w3c.github.io/vc-data-model/#integrity-of-related-resources

Would using the same mechanism on the data integrity side address your concerns?

**Comment by msporny** [comment]
We now state that application contexts should not be loaded from the network and should have known hashes in the Data Integrity spec, we also state in the VC spec that this is strongly advised (what @dmitrizagidulin says above). We can try to write more text to link the two items together, I'll double-check to see if the spec already says these two things after the most recent crop of PRs are merged.

**Comment by msporny** [comment]
@msporny wrote:
> I'll double-check to see if the spec already says these two things after the most recent crop of PRs are merged.

I just double-checked and we have some fairly strong language in the specification that addresses the initial issue raised, namely:

* The Data Integrity context MUST be cached with a cryptographic hash provided.
* Application-specific contexts SHOULD ensure that their JSON-LD context and vocabulary files are permanently cacheable
* Implementations MAY load application-specific JSON-LD context files from the network during development, but SHOULD permanently cache JSON-LD context files used in [conforming documents](https://w3c.github.io/vc-data-integrity/#dfn-conforming-document) in production settings

Those things are said in this section: https://w3c.github.io/vc-data-integrity/#contexts-and-vocabularies

This issue has been addressed (via previous PRs), closing.
