### ISSUE TITLE
Ensure proper capitalization of "context" and "vocabulary"

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-integrity#183]
@TallTed noted in https://github.com/w3c/vc-data-integrity/pull/172#pullrequestreview-1587734523 : 
> Note that context/s and vocabulary/ies are only capitalized in section titles in the JSON-LD spec, and I think that we should do the same. I have not applied this to the whole document

**Comment by msporny** [comment]
Yes, we need to make a pass through the spec and ensure that usage of "context" and "vocabulary" are all lower case (except for in section titles).

**Comment by seabass-labrax** [comment]
ETA for pull request Tuesday the 12th of December.

**Comment by msporny** [comment]
> Yes, we need to make a pass through the spec and ensure that usage of "context" and "vocabulary" are all lower case (except for in section titles).

I have done this pass today and can confirm that all usages of "context" and "vocabulary" are all lower case (except for in section titles and the few places where we do mean to capitalize them). Closing.
