### ISSUE TITLE
Example that demonstrates input(s) and what gets fed to the signature algorithms?

### ISSUE THREAD

**Issue by waywardmonkeys** [w3c/vc-data-integrity#19]
I think it would be helpful in understanding things if there were an example that demonstrated not just what the input was and the associated result with the signature, but something that showed what the intermediate values were and what gets fed to the hash algorithm.  (I know this would depend on the canonicalization algorithm, but even so, something to make sure that my implementation is doing the right thing step by step would be useful.)

**Comment by DePasqualeOrg** [comment]
> ISSUE 13
> The proof parameters should be included as headers and values in the data to be signed.

Is the data that is signed the entire canonicalized JSON-LD document, including the proof without the `proofValue` key and value?

**Comment by msporny** [comment]
This PR provides a start at addressing this issue: https://github.com/w3c/vc-di-eddsa/pull/24/files

A complete example, in the appendix, would be helpful for implementers.

**Comment by msporny** [comment]
Thanks to @Wind4Greg, we now have complete examples in the cryptosuite specifications, including all intermediate values:

https://w3c.github.io/vc-di-eddsa/#test-vectors

https://w3c.github.io/vc-di-ecdsa/#test-vectors

Those test vectors, along with all of the new algorithm text, should address this issue. I'm marking this issue as pending close. It will be closed in 7 days unless there are objections. If there is more to do here, please let us know.
