### ISSUE TITLE
Add explanation about why proof graphs are used

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-integrity#190]
The VC Data Model added an explanation related to VC graphs in PR https://github.com/w3c/vc-data-model/pull/1280. The Data Integrity specification should do the same.

**Comment by msporny** [comment]
This request is also related to a request by @iherman in this comment: https://github.com/w3c/vc-data-model/pull/1403#pullrequestreview-1797364583

**Comment by iherman** [comment]
This is also related to the discussion in https://github.com/w3c/vc-data-model/pull/1397#pullrequestreview-1815677016: the fact that the proof property's value is a named graph, i.e., that the property refers to a container property in JSON-LD parlance, must be clearly specified in the DI specification (it was, so far, part of the VCDM spec, but has been removed as part of https://github.com/w3c/vc-data-model/pull/1397).

**Comment by msporny** [comment]
PR #270 has been raised to address this issue. This issue will be closed once PR #270 has been merged.

**Comment by msporny** [comment]
PR #270 has been merged, closing.
