### ISSUE TITLE
Ambiguity resulting from signature -> proof rename

### ISSUE THREAD

**Issue by kimdhamilton** [w3c/vc-data-integrity#2]
This is a naming problem that I want to track and come back to.

I was confused reading this spec because of "proof" being used as a replacement for "signature". It connotes actions more along the lines of verification. For example:

"Proof Algorithm" replaces "Signature Algorithm", but it sounds like the act of proving (or verifying) vs signing.

**Comment by msporny** [comment]
Does this issue still exist in the current spec, @kimdhamilton?

Places where it appears are here:

https://w3c.github.io/vc-data-integrity/#terminology

and here:

https://w3c.github.io/vc-data-integrity/#proofs

and here:

https://w3c.github.io/vc-data-integrity/#algorithms

**Comment by kimdhamilton** [comment]
Looks resolved now; feel free to close
