### ISSUE TITLE
https://w3id.org/security/data-integrity/v1 is an octet-stream

### ISSUE THREAD

**Issue by jeswr** [w3c/vc-data-integrity#200]
https://w3id.org/security/data-integrity/v1 is published as an octet-stream rather than as application/ld+json. Could this please be resolved?

**Comment by TallTed** [comment]
Check your request headers. It looks like `application/ld+json` from here.
```pre
$ curl -LkI https://w3id.org/security/data-integrity/v1
HTTP/1.1 302 Found
Date: Mon, 18 Sep 2023 19:50:01 GMT
Server: Apache/2.4.29 (Ubuntu)
Access-Control-Allow-Origin: *
Location: https://w3c.github.io/vc-data-integrity/contexts/data-integrity/v1.jsonld
Content-Type: text/html; charset=iso-8859-1

HTTP/2 200 
server: GitHub.com
content-type: application/ld+json
...
```

**Comment by davidlehn** [comment]
This was fixed earlier today:
https://github.com/perma-id/w3id.org/pull/3583
https://github.com/w3c/vc-data-integrity/pull/201
