### ISSUE TITLE
representation-eddsa-rdfc-2022 Test Vector Issue

### ISSUE THREAD

**Issue by a-c-brown** [w3c/vc-data-integrity#204]
The [Canonical Proof Options](https://www.w3.org/TR/vc-di-eddsa/#example-canonical-proof-options-document) in the representation-eddsa-rdfc-2022 test vector appears to differ from that produced by the [JSON-LD Playground](https://tinyurl.com/2anawkyq) and [PyLD 1.1](https://github.com/digitalbazaar/pyld). 

If true please update Examples 12, 13, 14, 15, 16 , and 17. Thanks for your time.

![image](https://github.com/w3c/vc-data-integrity/assets/76745899/0ea736c1-aa2a-41e2-96e0-595424692ff6)

**Comment by dlongley** [comment]
@a-c-brown,

Yes, thanks for reporting this. This particular item (`cryptosuiteString`) was just adjusted in the context prior to preparing for CR and we were waiting to regenerate the test vectors until after it was done. There's one more PR in to adjust the context (#202), but that shouldn't affect this particular issue if we want to regen those test vectors now.

cc: @Wind4Greg

**Comment by a-c-brown** [comment]
> @a-c-brown,
> 
> Yes, thanks for reporting this. This particular item (`cryptosuiteString`) was just adjusted in the context prior to preparing for CR and we were waiting to regenerate the test vectors until after it was done. There's one more PR in to adjust the context (#202), but that shouldn't affect this particular issue if we want to regen those test vectors now.
> 
> cc: @Wind4Greg

Thanks @dlongley - those test vectors are extremely useful so I appreciate you having them available.

**Comment by Wind4Greg** [comment]
@a-c-brown Glad the test vectors are helping. Your review and confirmation of the vectors are important! The code used to generate the test vectors is open source and can be found at [EdDSA-Test-Vectors](https://github.com/Wind4Greg/EdDSA-Test-Vectors). @dlongley so its now a good time to regenerate all the EdDSA and ECDSA test vectors?

**Comment by dlongley** [comment]
@Wind4Greg,

Yes, I think we should regenerate them now -- I expect there to be a possible need to regen them again for proof chains because of the previous proof property PR that isn't in yet, but hopefully that will be the last time. The regen'd vectors that are for proof sets should be unchanged (I'd think) once that PR lands.

**Comment by msporny** [comment]
Test vectors were updated months ago in w3c/vc-di-eddsa#64, closing.
