### ISSUE TITLE
Verify Proof should take the cryptographic suite as a parameter

### ISSUE THREAD

**Issue by jyasskin** [w3c/vc-data-integrity#206]
The first mention of a cryptographic suite in https://www.w3.org/TR/vc-data-integrity/#verify-proof is "If the cryptographic suite ..." with nothing before that saying what the cryptographic suite is. I suspect it's passed in by the caller, and in that case the section's "required inputs" should mention that.

**Comment by jyasskin** [comment]
This will be fixed by the ["suite selection algorithm"](https://pr-preview.s3.amazonaws.com/jyasskin/vc-data-integrity/pull/227.html#dfn-suite-selection-algorithm) in #227.

**Comment by msporny** [comment]
PR #227 has been merged, closing.
