### ISSUE TITLE
The definition of "cryptographic suite" should include or point to its whole definition

### ISSUE THREAD

**Issue by jyasskin** [w3c/vc-data-integrity#207]
https://www.w3.org/TR/vc-data-integrity/#dfn-cryptosuite doesn't say what algorithms a cryptosuite needs to provide. It should point to https://www.w3.org/TR/vc-data-integrity/#cryptographic-suites as the rest of the definition, or the actual `<dfn>` tag should be in the section that lists the required algorithms. Otherwise it's hard to read uses of the term and know what to expect.

**Comment by msporny** [comment]
Fixed in e39d4d5c5b9d81394db36c1024f7b16c8fb81525, closing.
