### ISSUE TITLE
What's a "document"?

### ISSUE THREAD

**Issue by jyasskin** [w3c/vc-data-integrity#208]
https://www.w3.org/TR/vc-data-integrity/#dfn-unsecured-data-document and https://www.w3.org/TR/vc-data-integrity/#dfn-secured-data-document don't say what operations they support. We have some steps like "Set output.proof to the value of proof." and "Let unsecuredDocument be a copy of securedDocument with the proof value removed." that imply these are similar to JavaScript objects, but I couldn't find any direct statements to that effect.

**Comment by jyasskin** [comment]
This is fixed by #226, which includes:

> The algorithms defined below operate on documents represented as [JSON objects](https://www.rfc-editor.org/rfc/rfc8259#section-4). This specification follows [[JSON-LD-API](https://pr-preview.s3.amazonaws.com/jyasskin/vc-data-integrity/pull/226.html#bib-json-ld-api)] in representing a JSON object as an [[Infra](https://pr-preview.s3.amazonaws.com/jyasskin/vc-data-integrity/pull/226.html#bib-infra)] [map](https://infra.spec.whatwg.org/#ordered-map). An unsecured data document is a [JSON object](https://www.rfc-editor.org/rfc/rfc8259#section-4) with no "proof" [key](https://infra.spec.whatwg.org/#map-key). A secured data document is a [JSON object](https://www.rfc-editor.org/rfc/rfc8259#section-4) with a "proof" [key](https://infra.spec.whatwg.org/#map-key).

**Comment by msporny** [comment]
PR #226 has been merged, thank you for the PR @jyasskin! Closing.
