### ISSUE TITLE
Is the value space definition for `multibase` correct?

### ISSUE THREAD

**Issue by iherman** [w3c/vc-data-integrity#209]
The _value space_ definition of the [`multibase` datatype](https://www.w3.org/TR/vc-data-integrity/#multibase) currently says:

> **The value space**
>     An arbitrary binary data value.

I am not even sure I understand what that means (anything is a binary data in a computer). The lexical-to-value mapping actually says:

> Any element of the lexical space is mapped to the value space by base-decoding the value based on the base-decoding alphabet […]

in my understanding, the result of such a decoding is an integer number. As a result, the value space should say:

> Standard mathematical concept of integer numbers.

I reused the terminology used in the [definition of `xsd:integer`](https://www.w3.org/TR/xmlschema-2/#integer).

(My apologies not to have spotted this before, when this datatype was introduced.)

**Comment by msporny** [comment]
> As a result, the value space should say: Standard mathematical concept of integer numbers.

Agreed. I'll raise a PR that does this since it's more clear.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-10-17-vcwg-special#section1-2) on 2023-10-17

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.2. Is the value space definition for `multibase` correct? (issue vc-data-integrity#209)

_See github issue [vc-data-integrity#209](https://github.com/w3c/vc-data-integrity/issues/209)._




**Manu Sporny:** In the same vein -- issue 209. Ivan was reading about the multibase datatype in the spec, this has to do with specifying the value space for the datatype, we say it's "binary data", and Ivan is saying it's a mathematical concept of integer numbers and I would raise a PR to make a change to that. This does not effect implementations but it's important for us to get the text right.  
… A PR will be raised under the same scenario, raise the PR, get review and once I get confirmations it's ok, I will merge into the spec (before 7 day window).  
… Any objections?  

**Brent Zundel:** I am hearing no objections.  

**Manu Sporny:** That's it.  

**Brent Zundel:** Excellent! Thank you to the group.  
… I encourage folks to act quickly to get reviews in.  

</details>

**Comment by msporny** [comment]
PR #214 has been raised to address this issue. This issue will be closed after PR #214 has been merged.

**Comment by msporny** [comment]
PR #214 has been merged, closing.
