### ISSUE TITLE
Should the verification algorithm recursively check embedded objects?

### ISSUE THREAD

**Issue by cwebber** [w3c/vc-data-integrity#21]
Currently the existing signature algorithm verifies the toplevel document.  However, there may be signatures on embedded documents which also need to be checked.  Should we provide an option to recursively traverse the document and verify all embedded objects?  This seems like what we would want, in general, by default?

**Comment by msporny** [comment]
Algorithms now exist for Data Integrity proof verification and it's clear that those algorithms aren't recursive:

https://w3c.github.io/vc-data-integrity/#verify-proof

As a result, closing this issue.
