### ISSUE TITLE
Explain that data integrity secures underlying RDF graph

### ISSUE THREAD

**Issue by Sakurann** [w3c/vc-data-integrity#215]
This article explains it much better, but please add to the document (probably introduction?) that "data integrity" secures an RDF graph underlying the JSON document, as opposed to securing the JSON document itself and that it is an expected behavior that "the signature value does not change even if the JSON document changes as long as an underlying RDF graph does not change". https://medium.com/@markus.sabadello/json-ld-vcs-are-not-just-json-4488d279be43

**Comment by selfissued** [comment]
I agree that this should be done.

**Comment by dlongley** [comment]
>  "data integrity" secures an RDF graph ...

When using a cryptosuite that uses RDFC. You could also use one that uses JCS -- or both at the same time (two data integrity proofs on the same document).

**Comment by peacekeeper** [comment]
I also agree this should be explained.

And conversely, the "other effort" over at IETF should also explain that an SD-JWT/JWS can only secure the JSON document, not the underlying data of a JSON-LD document.

**Comment by msporny** [comment]
PR #271 has been raised to address this issue. This issue will be closed once PR #271 has been merged.

**Comment by msporny** [comment]
PR #271 has been merged, closing.
