### ISSUE TITLE
Find somewhere to parse bytes into an RDF dataset

### ISSUE THREAD

**Issue by jyasskin** [w3c/vc-data-integrity#222]
https://github.com/w3c/vc-data-model/pull/1338 passes a byte sequence as the ["secured data document"](https://www.w3.org/TR/vc-data-integrity/#dfn-secured-data-document) parameter to https://www.w3.org/TR/vc-data-integrity/#verify-proof. This algorithm uses it as an object with fields (without having parsed it) and then passes parts of it on to a transformation algorithm like https://www.w3.org/TR/vc-di-ecdsa/#transformation-ecdsa-rdfc-2019. This transformation algorithm passes that object into https://www.w3.org/TR/rdf-canon/#canon-algorithm, which expects to be operating on an [RDF dataset](https://www.w3.org/TR/rdf11-concepts/#dfn-rdf-dataset).

Some part of this chain needs to actually create the RDF dataset by calling into some algorithms from https://www.w3.org/TR/json-ld-api.

**Comment by msporny** [comment]
This has been fixed in https://github.com/w3c/vc-di-ecdsa/commit/4d266086fb22e8d7d142b2b78dabe1c3e65d7f23 and https://github.com/w3c/vc-di-eddsa/commit/fcf0ba08e0013d699a9e9b758e4fa99d3b317038. Closing.

**Comment by jyasskin** [comment]
I think those commits fix the second half of the problem, but as far as I can see, https://w3c.github.io/vc-data-model/#verification still passes _inputBytes_ to algorithms that expect ... well, they say they expect any map, but they pass it to https://www.w3.org/TR/json-ld11-api/#deserialize-json-ld-to-rdf-algorithm, which takes "a [map](https://infra.spec.whatwg.org/#ordered-map) node map, which is the result of the [Node Map Generation algorithm](https://www.w3.org/TR/json-ld11-api/#node-map-generation)".

**Comment by jyasskin** [comment]
Ok, I've filed what I think is a complete set of issues about the necessary type conversions. I'm happy for this issue to stay closed.
