### ISSUE TITLE
Ensure exposition text on relationship to VCs mentions checking verification relationship against proof purpose

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-data-integrity#229]
This may be obvious to some implementers, but we should make this more clear. This section:

https://w3c.github.io/vc-data-integrity/#relationship-to-verifiable-credentials

> There are some use cases where it is important to ensure that the [verification method](https://w3c.github.io/vc-data-integrity/#dfn-verification-method) used in a proof is associated with the [issuer](https://www.w3.org/TR/vc-data-model-2.0/#issuer) in a [verifiable credential](https://www.w3.org/TR/vc-data-model-2.0/#dfn-verifiable-credential), or the [holder](https://www.w3.org/TR/vc-data-model-2.0/#dfn-holders) in a [verifiable presentation](https://www.w3.org/TR/vc-data-model-2.0/#dfn-verifiable-presentation), during the process of [validation](https://www.w3.org/TR/vc-data-model-2.0/#issuer-0). One way to check for such an association is to ensure that the value of the controller property of a proof's [verification method](https://w3c.github.io/vc-data-integrity/#dfn-verification-method) matches the URL value used to identify the [issuer](https://www.w3.org/TR/vc-data-model-2.0/#issuer) or [holder](https://www.w3.org/TR/vc-data-model-2.0/#dfn-holders), respectively. This particular association indicates that the [issuer](https://www.w3.org/TR/vc-data-model-2.0/#issuer) or [holder](https://www.w3.org/TR/vc-data-model-2.0/#dfn-holders), respectively, is the controller of the [verification method](https://w3c.github.io/vc-data-integrity/#dfn-verification-method) used to verify the proof.

Should include the text: "...respectively, and that the verification method is expressed under a verification relationship that is acceptable given the proof's purpose."

EDIT: The above suggestion would replace the first "respectively" in the above text. Other text that achieves the same goal in a PR might also be acceptable to resolve this issue.

**Comment by TallTed** [comment]
I imagine a PR will make this plain, but I (and probably other readers) cannot yet be certain where you mean for the inclusion to be inserted. Possibly replacing the `respectively.` in the penultimate sentence?

**Comment by dlongley** [comment]
@TallTed,

Yes, sorry, that's what I meant (replacing the first "respectively" with the above suggestion) -- but, yes, a PR will make clear what the chosen text will be.

**Comment by TallTed** [comment]
(@dlongley — One big reason I needed to ask is that there are two instances of `respectively` in the quoted passage — `respectively. This` and `respectively, is`. I believe it's the first instance that you're replacing.)

**Comment by dlongley** [comment]
Yes, I've updated my comments to indicate that, thanks!

**Comment by msporny** [comment]
PR #273 has been raised to address this issue. This issue will be closed once PR #273 has been merged.

**Comment by msporny** [comment]
PR #273 has been merged, closing.
