### ISSUE TITLE
Missing "created" invalidates signature? 

### ISSUE THREAD

**Issue by cyberphone** [w3c/vc-data-integrity#23]
If I got this right, the absence of a "created" property requires the verifier to create an artificial ditto holding the current time.  Either "created" is unsigned (which would be strange), or validation will fail.

**Comment by melvincarvalho** [comment]
An argument for making created optional could be that there is already a timestamp in the data being signed, say a transaction

In systems with high throughput of tx you may want to avoid this duplication for performance reasons

**Comment by dlongley** [comment]
I think created should be optional, there are a number of use cases where its redundant or unnecessary.

**Comment by msporny** [comment]
At present `created` is mandatory in the data model section https://w3c.github.io/vc-data-integrity/#proofs ... but then inferred as being optional and only able to be mandated by a cryptosuite: https://w3c.github.io/vc-data-integrity/#algorithms

All that to say, the spec is in conflict with itself and we need to fix this to make sure it's optional (and the only thing that can make it mandatory is a specific cryptosuite).

**Comment by msporny** [comment]
PR #118 has been merged to address this issue, closing.

**Comment by David-Chadwick** [comment]
Since both expires and created are now optional, and we have validFrom and validUntil in the VCDM, then why not remove them entirely? The VC validity time can be the proxy for the proof validity time
