### ISSUE TITLE
cryptosuite missing from property list in 2.1 Proofs

### ISSUE THREAD

**Issue by HelgeKrueger** [w3c/vc-data-integrity#232]
See https://www.w3.org/TR/vc-data-integrity/#proofs

My understanding is that `cryptosuite` is mandatory for the proof elements.

**Comment by dlongley** [comment]
Yes, and we need to mention that `verificationMethod` can be optional like the other properties *if* the cryptosuite provides another mechanism by which to obtain it. In short, it's really `type` and `cryptosuite` that are hard requirements to enable extensibility.

**Comment by msporny** [comment]
> In short, it's really type and cryptosuite that are hard requirements to enable extensibility.

Hmm, no, `cryptosuite` is only required on `DataIntegrityProof`s... there are other types of proofs (like all the legacy ones) that don't require it. We'd break backwards compat if we required it for all proof objects.

**Comment by msporny** [comment]
PR #266 was raised, discussed, and merged to address this issue. Closing.
