### ISSUE TITLE
Possible Informative Text on Proof Chains and Sets

### ISSUE THREAD

**Issue by Wind4Greg** [w3c/vc-data-integrity#234]
Folks (@TallTed, @msporny, @dlongley), a while back when we put in normative changes to the proof chain construction and verification algorithms there was some interest in explanatory (informative) text explaining the security differences between proof sets and proof chains and how chains work. Below is an attempt at such an explanation. Unfortunately it is longer than either creation or verification algorithm. Hence before writing a full PR for this I've got two questions: (1) Does this help understanding enough to warrant adding this informative text to the document? (2) If it is desired to add it to the document. Where should we put it? (at the end of the proof chains section or in the security considerations section)

Also if we want to include this type of explanation any suggestions are welcome.

Cheers Greg B. (@Wind4Greg)

## Understanding Proof Sets and Proof Chains

Proof sets and chains allow multiple proofs to be carried in a VC, i.e.,
instead of a single *proof* included in the signed VC we can have an array of proofs as shown in the previous examples. The elements of this array can be either members of *proof set* or a *proof chain*. The purpose of this section is to explain the intended use of each of these entities and, in particular, their differing security properties. These differing security properties lead to differences in the processing in section <a href="#add-proof-set-chain></a>.

We are going to represent VCs and their proofs in a highly abbreviated manner so that the key security properties can be observed.

We consider a scenario with three signatories: a CEO, a CFO, and a VP of Engineering. Each will need to have a public and private key pair for signing a document. We denote the private/public keys of each of these signatories by  *priv/pubCEO*, *priv/pubCFO*, and *priv/pubVPE* respectively.

When constructing a *proof set* where each of the signatories signs a document without concern we construct a proof symbolically as:

```javascript
{
    "type": "DataIntegrityProof",
    "cryptosuite": "jcs-eddsa-2022",
    "created": "2023-03-05T19:23:24Z",
    "proofPurpose": "assertionMethod",
    "verificationMethod": pubCEO,
    "proofValue": signature(privCEO, document)
  }
```

Where *pubCEO* is used as a placeholder for a reference that resolves to the CEO's public key and `signature(priv, doc)` denotes the computation of a digital signature by a particular data integrity cryptosuite using a particular private key over a particular document. The *type*, *cryptosuite*,  *created*, and *proofPurpose* attributes do not factor into our discussion so we will omit them. In particular below we show all the proofs in a *proof set* on a document that has been signed by the VP of engineering, CFO, and CEO:

```javascript
{ // Rest of VC document not shown, this proof set will verify
  "proof": [
  {verificationMethod: pubVPE, proofValue: signature(privVPE, document)},
  {verificationMethod: pubCFO, proofValue: signature(privCFO, document)},
  {verificationMethod: pubCEO, proofValue: signature(privCEO, document)}]
}
```

The *holder* or any other intermediary receiving a signed VC containing a *proof set* is able to remove any of the *proofs* within the set prior to passing it on to another entity and this VC will still verify. This may or may not be the intent. For the signatories sending a birthday card to a valued employee this is probably fine. If we are trying to model a business process where approvals ascend the company hierarchy this would not be ideal since any intermediary could remove signatures from the *proof set* and still have it verify, i.e., below it looks like the CFO and CEO just approved something without the VP of engineering's concurrence.

```javascript
{ // Rest of VC document not shown, this proof set will verify
  "proof": [
  {verificationMethod: pubCFO, proofValue: signature(privCFO, document)},
  {verificationMethod: pubCEO, proofValue: signature(privCEO, document)}]
}
```

We can introduce a "dependency relation" between *proofs* in a *proof set* by assigning the proof that another proof relies on, i.e., the *dependent proof*, an *id* and the *relying proof* will have a list (or single item) denoting *previousProofs*. Such *dependency chains* can have arbitrary depth. The **intent** of such a *proof chain* is to model an approval chain in a business process or a notary witnessing analog signatures. In such cases we CANNOT allow the *proofs* that are relied upon to be **substituted** with other proofs or removed.

Let's see how a *proof chain* is constructed where the VP of Engineering signs off on the document first, based on VP of engineering's signature and a review the CFO signs off of the document, finally based on both the prior signatures and a review the CEO signs off on the document. Since others will be referring to the VP of engineering's signature we need to add a *id* to the proof options. First the VC of engineering signs the VC:

```javascript
{ // Rest of VC document not shown, this proof set will verify
  "proof": {id: 0, verificationMethod: pubVPE, proofValue: signature(privVPE, document)}
}
```

Next, the CFO receives the document, verifies that the VP of engineering signed it and signs it based on a review and on the VP of Engineering signing. For this we need to set up the *proof chain* by indicating a dependency on the proof in the document just received, i.e., `previousProof = 0`. The processing algorithm has us "bind" the previous proof to the unsigned document. Denote the this proof by *proof0* and "binding" this information to the document by `document + proof0`:

```javascript
{ // Rest of VC document not shown
  "proof": [
  {id: 0, verificationMethod: pubVPE, proofValue: signature(VP_Eng, document)},
  {id: 1, verificationMethod: pubCFO, previousProof: 0, proofValue: signature(privCFO, document + proof0)}]
}
```

Now when the CEO validates the received the VC with the above *proof chain* they will check that the CFO signed based on the VP of Engineering signing it. First, they will check the proof/signature with `id = 0` against the public key of the VP of Engineering. Note that this proof/signature is over the original document. Next, the CEO will check the proof/signature `id = 1` against the public key of the CFO. However, to make sure that the CFO signed with the document knowing, and with proof, that the VP of engineering signed we verify this signature/proof over the combination of the document and *proof0*. If validation is successful the CEO signs producing a proof over the document and *proof1* (the proof with `id = 1`). The final signed chain looks like:

```javascript
{ // Rest of VC document not shown
  "proof": [
  {id: 0, verificationMethod: pubVPE, proofValue: signature(VP_Eng, document)},
  {id: 1, verificationMethod: pubCFO, previousProof: 0, proofValue: signature(privCFO, document + proof0)},
  {id: 2, verificationMethod: pubCEO, previousProof: 1, proofValue: signature(privCEO, document + proof1)},
  ]
}
```

The recipient of this VC then validates it in a similar way as above but with one extra step.

**Comment by TallTed** [comment]
Seems like a potential appendix, to me. Purely informative, so after CR should not be a problem. Still, the sooner it's in a collaboratively editable place (wiki, git-managed md or html, etc.), the better, as I noticed a number of minor errors above that may not be re-noticed during later reviews.

**Comment by msporny** [comment]
PR #237 has been merged, closing.
