### ISSUE TITLE
Replace jcs-eddsa-2022 with eddsa-jcs-2022 in examples

### ISSUE THREAD

**Issue by silverpill** [w3c/vc-data-integrity#239]
Example 2 in section **2.1 Proofs** uses `jcs-eddsa-2022` cryptosuite. This is the old cryptosuite name that was changed to `eddsa-jcs-2022` in [vc-di-eddsa](https://www.w3.org/TR/vc-di-eddsa/).

**Comment by Wind4Greg** [comment]
Anyone know where these examples came from? I've got open source code to generate the test vectors for the specific crypto-suites, but not the examples. I could take this on but would be quicker for the original source to do it.

**Comment by msporny** [comment]
Fixed in a6b7808f6e663d8f5cf9e8dfc557b0449db6aa40 , closing.
