### ISSUE TITLE
Mentioning how to retrieve the public key

### ISSUE THREAD

**Issue by cwebber** [w3c/vc-data-integrity#24]
[Section 7](https://w3c-dvcg.github.io/ld-signatures/#signature-verification-algorithm) mentions retrieval of the public key, and obviously that's a pretty key part of this process.

I've expressed [my impressions](https://github.com/w3c/activitypub/issues/203#issuecomment-297553229) of how to retrieve the public key; are they correct?  It would be good to have this written up in the document.

**Comment by msporny** [comment]
The algorithm is now outlined in this section of the specification:

https://www.w3.org/TR/vc-data-integrity/#retrieve-verification-method

Closing this issue based on this normative specification text existing now. Please re-open if you disagree.
