### ISSUE TITLE
Checking a historical artifact...

### ISSUE THREAD

**Issue by iherman** [w3c/vc-data-integrity#242]
We already have, currently, a discrepancy in the security vocabulary. The term defined in the vocabulary is [`expiration`](https://w3id.org/security#expiration) but it is referred to in the [security vocabulary context file](https://w3id.org/security/data-integrity/v2) as `expires`. The vocabulary contains the following comment:

> Historically, this property has often been expressed using expires as a shortened term in JSON-LD. Since this shortened term and its mapping to this property are in significant use in the ecosystem, the inconsistency between the short term name (expires) and the property identifier (...#expiration) is expected and should not trigger an error.

I realized today that there are four more similar discrepancies between the [context file](https://w3id.org/security/data-integrity/v2) and the [vocabulary](https://w3id.org/security) namely

| short name for JSONLD in the context | vocabulary term used in the context | current vocabulary term |
| --- | --- | --- |
| authentication | authenticationMethod | authentication | 
| capabilityInvocation | capabilityInvocationMethod | capabilityInvocation | 
| capabilityDelegation | capabilityDelegationMethod | capabilityDelegation | 
| keyAgreement | keyAgreementMethod | keyAgreement | 

_I presume_ that the vocabulary file should be changed, and it should refer to `...Method` with a similar comment. However, I would prefer to get a reinforcement from the WG before doing a change.

@dlongley @msporny

**Comment by dlongley** [comment]
Yes, the vocabulary needs to be updated to reflect the vocab terms used in the context as stated above in the table.

**Comment by iherman** [comment]
This issue is being taken care of in #243; it can be closed if and when the PR is merged.

**Comment by msporny** [comment]
PR #243 has been merged, closing.
