### ISSUE TITLE
Editorial: `type` must be a URL

### ISSUE THREAD

**Issue by iherman** [w3c/vc-data-integrity#245]
[§2.3.1 Verfication Methods](https://www.w3.org/TR/vc-data-integrity/) says, for the `type` property:

> The value of the type property MUST be a [string](https://infra.spec.whatwg.org/#string) that references exactly one [verification method](https://www.w3.org/TR/vc-data-integrity/#dfn-verification-method) type.

This may be misunderstood. I believe the text should say (to stay with the style used elsewhere)

> The value of the `type` MUST be a [string](https://infra.spec.whatwg.org/#string) that conforms to the [[URL](https://www.w3.org/TR/vc-data-integrity/#bib-url)] syntax, and that references exactly one [verification method](https://www.w3.org/TR/vc-data-integrity/#dfn-verification-method) type.

**Comment by iherman** [comment]
Actually, the text may be clearer if, at that point, it also linked to the two verification method types that this specification defines (`Multikey` and `JsonWebKey`), and others may be defined by the community.

**Comment by iherman** [comment]
PR has been raised; if merged this issue can be closed.

**Comment by msporny** [comment]
PR #254 has been merged, closing.
