### ISSUE TITLE
Editorial: remove a reference to external value

### ISSUE THREAD

**Issue by iherman** [w3c/vc-data-integrity#246]
[Example 13](https://www.w3.org/TR/vc-data-integrity/#example-embedding-and-referencing-verification-methods) says

> // external (property value)

for `Multikey`. I presume what this means is that the term is defined somewhere else, but that is not correct. This is a reference to a class defined in this specification. Better remove it.

**Comment by msporny** [comment]
Fixed in a8600066a4da19dcdb6dd0684937303d50f203e3. Closing.
