### ISSUE TITLE
Editorial: add a reference to the cryptosuites in the section on Multikeys

### ISSUE THREAD

**Issue by iherman** [w3c/vc-data-integrity#251]
The DI spec introduces [two verification methods](https://www.w3.org/TR/vc-data-integrity/#dfn-verification-method): [`JsonWebKey`](https://www.w3.org/TR/vc-data-integrity/#jsonwebkey) and [`Multikey`](https://www.w3.org/TR/vc-data-integrity/#jsonwebkey)

`JsonWebKey` is, conceptually, simple. There is an external specification, JWK, which defines how to store crypto keys. For the reader of the DI spec, this is easy.

`Multikey` is very different. The corresponding section only says that the material (e.g., keys) must be stored in [Multibase](https://www.w3.org/TR/vc-data-integrity/#multibase-0) but nothing is said _what_ is stored in multibase. For the reader of the DI spec, this is incomprehensible.

It turns out that the missing "meat" is defined elsewhere, namely in the respective sections of the cryptosuites specs (see, e.g., the [ecdsa case](https://www.w3.org/TR/vc-data-integrity/#multibase-0)). But finding that information is far from trivial.

Proposal: add a text in the Multikeys' section of the DI spec, making it clear that the cryptosuite specifications are responsible to give a detailed specification of what and how should be encoded as a, say, `publicKeyMultibase` value.

**Comment by msporny** [comment]
PR #257 has been merged to address this issue, closing.
