### ISSUE TITLE
Wrong cryptosuite name in example

### ISSUE THREAD

**Issue by iherman** [w3c/vc-data-integrity#252]
[Example 4](https://www.w3.org/TR/vc-data-integrity/#example-a-simple-signed-json-ld-data-document) refers to `ecdsa-2019` for cryptosuite (and there is also a reference to it in the preceding section). However, the [ECDSA spec](https://www.w3.org/TR/vc-di-ecdsa/) only defines `ecdsa-rdfc-2019`, `ecdsa-jcs-2019`, and `ecdsa-sd-2023`. I presume that in this case the right reference should be `ecdsa-rdfc-2019`.

I did not do an exhaustive search for the other references, there might be more such discrepancies.

**Comment by iherman** [comment]
There were only a few references to be changed after all: the two raised in the issue, plus a `bbs-2023` (which was `bbs-2022`).

I have created a PRL #253. This issue can be closed if and when that PR is merged.

**Comment by msporny** [comment]
PR #253 has been merged, closing.
