### ISSUE TITLE
(Editorial) would it be possible to annotate the input and output types for Javascript examples?

### ISSUE THREAD

**Issue by iherman** [w3c/vc-data-integrity#263]
I am looking at [example 20](https://www.w3.org/TR/vc-data-integrity/#example-an-implementation-of-the-general-base-encoding-algorithm-above-in-javascript) and [example 21](https://www.w3.org/TR/vc-data-integrity/#example-an-implementation-of-the-general-base-decoding-algorithm-above-in-javascript): it would greatly help comprehension if the exact type of the input arguments, as well as the output value, was properly defined. I am not asking to turn this into TypeScript, but at least follow the JSDoc syntax. It can be as simple as:

```js
/**
 * @param {UInt8Array} bytes 
 * @param {number} targetBase 
 * @param {string} baseAlphabet 
 * @returns string
 */
function baseEncode(bytes, targetBase, baseAlphabet) {
   …
```

(Provided I interpret the input argument types properly. Is it an `UInt8Array` or the generic `ArrayBuffer`?)

**Comment by msporny** [comment]
PR #267 was raised to address this issue. That PR has been processed and merged. Closing.
