### ISSUE TITLE
What attributes are included in proof options?

### ISSUE THREAD

**Issue by dbaturin** [w3c/vc-data-integrity#27]
It's not clear what attributes to include in proof options. I get that additional attributes are included but what about the required ones?
Let's say I'm trying to verify credential with `Ed25519Signature2018` proof.

> The proof options MUST contain an identifier for the public/private key pair, and an [ISO8601] combined date and time string, created, containing the current date and time, accurate to at least one second, in Universal Time Code format. A domain might also be specified in the options.

This tells me that `verificationMethod` and `created` attributes are definitely included for linked data signature

But what about `type` and `proofPurpose`? Definition looks like they are not a part of proof options.

> proof options
    A set of options that is included in the proof data. These options might include controller, challenge, domain, or other data that is specific to the proof format. 

However this line looks like a whole proof node is expected as input

> If the proof value parameter, such as jws, exists in options, remove the entry

So how should my options look before normalization?
Like this:
```
{
    "type": "Ed25519Signature2018",
    "proofPurpose": "assertionMethod",
    "created": "2019-08-23T20:21:34Z",
    "verificationMethod": "did:example:123456#key1"
}
```
Like this:
```
{
    "created": "2019-08-23T20:21:34Z",
    "verificationMethod": "did:example:123456#key1"
}
```
Or am I missing something?

I think either it should be explicitly specified which entries to remove in `Create Verify Hash Algorithm` or the definition should be changed for something like "all proof attributes except proof value".

**Comment by OR13** [comment]
@dbaturin yes, sadly the create verify data algorithm definition is not as precise as we would like.... 

I resolve this by testing signatures across implementations, for example with RSA:

https://github.com/transmute-industries/RsaSignature2017/blob/master/src/common.js#L14

this  example is old, but shows how this function is computed if you are not using a higher order library that does this automatically for you... examples of such libraries are:

- https://github.com/transmute-industries/vc.js
- https://github.com/digitalbazaar/vc-js
- https://github.com/hyperledger/aries-framework-go

I strongly suggest comparing to a known good implementation for example, Ed25519Signature2018 with keys from https://w3c-ccg.github.io/did-method-key/#ed25519-x25519

and one of the libraries linked, to make sure you can verify "theirs" and they can verify "yours".

**Comment by msporny** [comment]
We have updated the algorithms to be much more specific about what should be contained in proof options here:

https://w3c.github.io/vc-data-integrity/#generate-proof

and here:

https://w3c.github.io/vc-di-eddsa/#proof-generation

These algorithms are still being refined. We'll leave this issue open until we feel like the algorithms are finalized.

**Comment by msporny** [comment]
There has been significant work on the algorithms over the past several months, and the proof options (and what goes in them) has been detailed in the current base specification (search for "proof options"):

* https://www.w3.org/TR/vc-data-integrity/#add-proof
* https://www.w3.org/TR/vc-data-integrity/#verify-proof

The cryptosuite specifications also detail what values are included in "proof options" (again, search for "proof options"):

* https://www.w3.org/TR/vc-di-eddsa/#eddsa-2022
* https://www.w3.org/TR/vc-di-ecdsa/#ecdsa-2019

The original issue asked which attributes are in proof options, the algorithms now specify exactly what properties proof options should contain. The issue will be closed in 7 days unless there is feedback that more needs to be done here.
