### ISSUE TITLE
Proof Type

### ISSUE THREAD

**Issue by clehner** [w3c/vc-data-integrity#28]
[§ 9. Creating New Proof Types](https://w3c-ccg.github.io/ld-proofs/#creating-new-proof-types) says that the `type` attributes of a proof type should have the value `ProofSuite`. But the [example](https://w3c-ccg.github.io/ld-proofs/#example-7) below has `"type": "Ed25519VerificationKey2018"`. Which is correct?

**Comment by msporny** [comment]
The current specification has removed all language related to specifying the new proof types using RDF. Doing so, while academically pure, was unnecessary and complicated the creation of cryptography suites. Instead, we rely on a cryptosuite specification to define concrete values now.

Closing as this guidance is no longer given in the current specification.
