### ISSUE TITLE
Official version is out of sync

### ISSUE THREAD

**Issue by iherman** [w3c/vc-data-integrity#284]
There seems to be a github action error somewhere for a while: the /TR version of the spec is of the 20th of June, and the editors' draft is from the 7th of July.  This should be taken care of asap, it makes the checking of PRs complicated...

cc @msporny @Wind4Greg

**Comment by msporny** [comment]
Fixed in 3ec2f9bdd918d105fe88a98b7ea6a4613726813c.

New version was just published here: https://www.w3.org/TR/2024/CRD-vc-data-integrity-20240709/

Closing.
