### ISSUE TITLE
Error in the definition of the "unsecured document"

### ISSUE THREAD

**Issue by iherman** [w3c/vc-data-integrity#287]
(This issue comes from w3c/vc-data-model#1519, more exactly https://github.com/w3c/vc-data-model/pull/1519#discussion_r1667664777).

The term `unsecuredDocument` is defined in [§4 Algorithms](https://www.w3.org/TR/vc-data-integrity/#dfn-unsecured-data-document) of the DI specification as follows:

> An unsecured data document is a [map](https://infra.spec.whatwg.org/#ordered-map) with no proof [key](https://infra.spec.whatwg.org/#map-key).

This definition goes wrong for the case when proofs are chained (and if the intention is to prove the previous `proof` entry of the chain). See again https://github.com/w3c/vc-data-model/pull/1519#discussion_r1667664777 for more details on the effects on cryptosuites.

Also, it is not immediately obvious what happens in the case of a Verifiable Presentation: in a VP, on the top level there is no proof key in the data, because all other instantiations of the `proof` key (or equivalent) appear only "behind" the `verifiableCredential `key, so to say. Which does mean that the `unsecuredDocument` does in fact _include_ the proofs for the VCs in the Presentation, but it may be worth spelling this out.

I would also note that there is a duplication of definitions between this and the definitions in [§5.12 Securing Mechanism Specifications](https://www.w3.org/TR/vc-data-model-2.0/#securing-mechanism-specifications) (whether w3c/vc-data-model#1519 gets merged or not). This is a possible source of errors. I would propose we choose one of the sections for the formal definition, clean it up, and then refer to it from the other place.

cc @dlongley @msporny @TallTed

**Comment by iherman** [comment]
Note, on the choice of where we want to have the final definition:

- §5.12 contains normative text on the definition of securing mechanisms in general
- At the moment, ecdsa and eddsa (I have not checked bbs) refer to the concept of `unsecuredDocument` (defined in §4) in their specifications on _what_ to secure

This means that

1. If we define the normative behavior v.a.v. chained proofs in §5.12, that will be valid _for all cryptosuites_. 
2. At the moment, cryptosuites _may_ decide to ignore the concept of `unsecureDocument` in their specification, i.e., not to secure chained proofs. 

I.e, if we think we want to keep it open for cryptosuites (i.e., keep (2)) then the formal definition should not be in §5.12 but, rather, in §4, and a remark should be added in §5.12 making it clear that cryptosuites may choose something else than what is in §4.

I must admit, I do not know whether we really want to maintain (2). Is there really a use case? I would think that having an identical behavior _for all cryptosuites_ in this respect would be a plus. But that is just a personal feeling, to an opinion based on use cases.

**Comment by iherman** [comment]
(I just realized that this error is in fact a discrepancy between the DI and the VCDM documents, although it grew out of a discussion on the VCDM repo. We may want to move this to the other repo, but whatever we decide to do, it will probably affect both documents...)

**Comment by iherman** [comment]
I have to conclude that I was wrong. The term `unsecuredDocument`, the way it is used, seems to be correct, although it does make your mind work for Verifiable Presentations. The case of proof chains and set is taken care of (I believe) in the separate section which, I hope, is correct. 

Referring back to the VCDM section is probably a no no, because the intention of the DI spec is to work for JSON-LD at large, and not only for VCDM...

Propose closing.

@msporny w.d.y.t.?

**Comment by msporny** [comment]
@iherman wrote:
> Propose closing.

Let's keep it open until I'm able to review the language. When it was written, I was probably not thinking of documents that legitimately already contain proofs (VPs, or proof chains). A minor language fix/update might be useful.

**Comment by iherman** [comment]
In any case, I move this issue to the DI issue list. The real question is how the unsecure document is defined and used, which is not a VCDM term. My bad.

**Comment by iherman** [comment]
So here is where I still see a problem:

- In step (6) of [§4.2 Add Proof Set/Chain](https://www.w3.org/TR/vc-data-integrity/#add-proof-set-chain) the `unsecuredDocument` map gets its `proof` member set. Per the current specification, the map becomes then a _securedDocument_, ie, the map's name is a misnomer. That is not, strictly speaking, an error, but it is ugly.
- In step (7) `unsecuredDocument` is passed on the [§4.1 Add Proof](https://www.w3.org/TR/vc-data-integrity/#add-proof) algorithm, which expects an `unsecuredDocument` as a required input. What it gets is not an unsecured document. I.e., if I implemented these algorithms in a typed language verbatim (e.g., in TypeScript) then I would get an error.

cc @dlongley @msporny 

(B.t.w., a bit of editorial issue with §4.2: shouldn't the description say that this algorithm has to be run incrementally with all elements on the chain? The algorithm only defines how I add _one_ extra proof entry to a credential, resulting in a credential with, say, two proofs; then the algorithm has to be run again for a third proof, if applicable, and so on...)

**Comment by msporny** [comment]
PR #292 has been raised to address this issue. This issue will be closed once PR #292 has been merged.

**Comment by msporny** [comment]
PR #292 has been merged, closing.
