### ISSUE TITLE
Ambiguous step in proof chain creation

### ISSUE THREAD

**Issue by iherman** [w3c/vc-data-integrity#289]
Step (6) in [§4.2 Add Proof Set/Chain](https://www.w3.org/TR/vc-data-integrity/#add-proof-set-chain) says:

> Set _unsecuredDocument.proof_ to _matchingProofs_.

where _matchingProofs_ is defined to be a list containing, in essence, the list of proofs. Quoting the definition from step (1)

> If _proof_ is a list, copy all the elements of _proof_ to _allProofs_. If _proof_ is an object add a copy of that object to _allProofs_.

The elements of _allProofs_ are then copied to _matchingProofs_ in steps (4) and (5).

The question that comes up is: what does _matchingProofs_ contain ***exactly***? The problem I have is that the answer  may be different on whether I take a “JSON View” or an “RDF Dataset” view (the latter is generated from JSON-LD using the relevant `@context`.

In JSON(-LD), I have

```json
{
   …
   "proof": [{
	   … claims of the proof
   }]
}
```

So when I read the aforementioned statements with a strict JSON goggle on, the interpretation is that _unsecuredDocument.proof_  includes all the claims of the proof. 

The situation is a bit different in the RDF Dataset view, i.e., after the JSON-LD processor has generated the RDF quads. Indeed, the value, i.e., the object, of the RDF triples containing the `proof` property ***is a graph reference*** that ***contains*** a  _DataIntegrityProof_ object with the claims. See a [playground example](https://json-ld.org/playground/#startTab=tab-nquads&json-ld=%7B%22%40context%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2Fns%2Fcredentials%2Fv2%22%5D%2C%22id%22%3A%22http%3A%2F%2Fexample.gov%2Fcredentials%2F3732%22%2C%22type%22%3A%5B%22VerifiableCredential%22%5D%2C%22issuer%22%3A%22did%3Aexample%3A6fb1f712ebe12c27cc26eebfe11%22%2C%22proof%22%3A%7B%22type%22%3A%22DataIntegrityProof%22%2C%22id%22%3A%22https%3A%2F%2Fexample.gov%2FmyProof%22%2C%22cryptosuite%22%3A%22eddsa-rdfc-2022%22%2C%22created%22%3A%222021-11-13T18%3A19%3A39Z%22%2C%22verificationMethod%22%3A%22https%3A%2F%2Funiversity.example%2Fissuers%2F14%23key-1%22%2C%22proofPurpose%22%3A%22assertionMethod%22%2C%22proofValue%22%3A%22z58DAdFfa9SkqZMVPxAQp...jQCrfFPP2oumHKtz%22%7D%7D) which includes:

```turtle
<http://example.gov/credentials/3732> <https://w3id.org/security#proof> _:b0 .
…
<https://example.gov/myProof> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://w3id.org/security#DataIntegrityProof> _:b0 .
```

See also [Figure 6](https://www.w3.org/TR/vc-data-model-2.0/#info-graph-vc) in the VCDM.

This means that, strictly speaking, the statement above means to add the graph ***names*** (`_:b0` in the example above), without the claims themselves, to _unsecuredDocument_.

I presume the correct interpretation is the pure JSON view. But an implementer of DI in a pure RDF environment has to be sure about this, because the distinction, obviously, affects interoperability. The “translation” of the JSON view into RDF is that the implementation has to add a reference to the proof graph ***and*** the content of the Proof Object (i.e., all the claims) in the forms of quads (referring to `_:b0` as a graph component).

I propose that this detail should be made at least in an editorial note, in the algorithm.

(I wonder whether a similar issue may be found elsewhere in the algorithmic description, which may require a more general note for the whole algorithm instead of only in this section.)

@msporny @dlongley @Wind4Greg

**Comment by msporny** [comment]
Yes, we expect the "JSON view" to happen (since it ends up making the right thing happen for JSON-LD). What would you like the editorial note to say, @iherman? Something like: "literally copy the claims to the proof object, don't just inject a reference to the graph names?"

**Comment by iherman** [comment]
> Yes, we expect the "JSON view" to happen (since it ends up making the right thing happen for JSON-LD). What would you like the editorial note to say, @iherman? Something like: "literally copy the claims to the proof object, don't just inject a reference to the graph names?"

Almost... I think, to be more clear, we should refer to the proof graph rather than proof object (which is not the right term on the rdf level)

"literally copy the claims contained by the proof graphs, don't just inject a reference to the graph names."

**Comment by iherman** [comment]
#296 has been raised. If and when that PR is merged, this issue may be closed.

**Comment by msporny** [comment]
PR #296 has been merged, closing.
