### ISSUE TITLE
domain should be a string or array

### ISSUE THREAD

**Issue by awoie** [w3c/vc-data-integrity#29]
To allow multiple recipients of the LD-Proof similar to the `aud` claim in JWT land (see IANA). I want to avoid creating multiple proofs for each domain individually.

**Comment by msporny** [comment]
@awoie is this request still pertinent? The current specification only allows a single string for `domain`. Do you still have a use case where you want to create a single proof for multiple domains?

**Comment by msporny** [comment]
2nd attempt at requesting feedback from @awoie -- ping. Any thoughts on this feature, do we still need it?

**Comment by msporny** [comment]
The Editors of the specification discussed this last week and decided that it wouldn't do harm to allow there to be multiple domains listed for the property. A PR will be raised to enable that use case.

**Comment by msporny** [comment]
PR #156 has been raised to address this issue. This issue will be closed once PR #156 has been merged.

**Comment by msporny** [comment]
PR #156 has been merged. Closing.
