### ISSUE TITLE
Unused reference [mimesniff]

### ISSUE THREAD

**Issue by selfissued** [w3c/vc-data-integrity#306]
The [mimesniff] reference at https://w3c.github.io/vc-data-integrity/#normative-references is not used in the specification.  It should be removed.

**Comment by msporny** [comment]
The [mimesniff] reference is used for the "media type" and "parameters" references in 

https://w3c.github.io/vc-data-integrity/#verify-proof

here:

![image](https://github.com/user-attachments/assets/50d32dbf-c226-4c44-b4ae-84cbfebcf971)

and here:

![image](https://github.com/user-attachments/assets/beffd344-0d1a-482e-98e6-ccaf8683400b)

Removing the reference would cause the following ReSpec errors to be thrown.

![image](https://github.com/user-attachments/assets/e3332dc7-9b64-4a8d-9ee5-1e16efc140db)

The reference is correct and should remain. Closing.

**Comment by selfissued** [comment]
Yes, apparently it's used silently, but "[mimesniff]" doesn't appear in the body of the spec.  The spec should add it where it's used.

**Comment by msporny** [comment]
Reopening to add a explicit reference to MIMESNIFF in the section identified above.

**Comment by msporny** [comment]
Fixed in 25e2237f56766ab08dd09d34e0a3b23aee1c7e60. Closing.
