### ISSUE TITLE
Move Contexts and Vocabularies content about Data Integrity to the Data Integrity specification

### ISSUE THREAD

**Issue by selfissued** [w3c/vc-data-integrity#308]
This content, currently in the Controller Document spec, actually belongs in the Data Integrity spec, per https://github.com/w3c/controller-document/issues/67#issuecomment-2322961540 .

> URL: https://w3id.org/security/data-integrity/v2 (application/ld+json)
> SHA2-256 Digest: 67f21e6e33a6c14e5ccfd2fc7865f7474fb71a04af7e94136cb399dfac8ae8f4

**Comment by msporny** [comment]
The data-integrity/v2 hash already exists in the Data Integrity specification in this section:

https://w3c.github.io/vc-data-integrity/#contexts-and-vocabularies

Here is the text from the current specification:

![image](https://github.com/user-attachments/assets/e5648a58-af90-497b-be9b-d84413ab0dba)

Closing.
