### ISSUE TITLE
Remove lowercase must text

### ISSUE THREAD

**Issue by PatStLouis** [w3c/vc-data-integrity#318]
The [unlinkability section](https://www.w3.org/TR/vc-data-integrity/#unlinkability) has a lowercase must keyword.

> [...] This characteristic is called unlinkability which ensures that no correlatable data are used in a digitally-signed payload while still providing some level of trust, the sufficiency of which _must_ be determined by each verifier. 

I would suggest to:
A) Make this a normative statement
B) Change the wording to abstract the word `must` to avoid confusion

Suggested change:
> [...] the sufficiency of which ~must~ **has to** be determined by each verifier.

**Comment by dlongley** [comment]
+1 to rewording to avoid the use of "must" in the above referenced sentence. Neither RFC2119 language nor a testable statement were intended. I think "has to" is acceptable clarifying language.

**Comment by peacekeeper** [comment]
Agree with @dlongley

**Comment by msporny** [comment]
PR #319 was raised to address this issue, closing.
