### ISSUE TITLE
vc:proof scope

### ISSUE THREAD

**Issue by bertvannuffelen** [w3c/vc-data-integrity#33]
Hi,

In the spec there are references to different proofing techniques, but it is unclear for me  what is proofs and how it guarantees that the data is sound.

In example 11  (see https://www.w3.org/TR/vc-data-model/#proofs-signatures) the proof is embedded in the json structure. It is unclear on what representation is the proof build. 

```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "id": "http://example.gov/credentials/3732",
  "type": ["VerifiableCredential", "UniversityDegreeCredential"],
  "issuer": "https://example.edu",
  "issuanceDate": "2010-01-01T19:23:24Z",
  "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "degree": {
      "type": "BachelorDegree",
      "name": "Bachelor of Science and Arts"
    }
  },
  "proof": {
    "type": "Ed25519Signature2020",
    "created": "2021-11-13T18:19:39Z",
    "verificationMethod": "https://example.edu/issuers/14#key-1",
    "proofPurpose": "assertionMethod",
    "proofValue": "z58DAdFfa9SkqZMVPxAQpic7ndSayn1PzZs6ZjWp1CktyGesjuTSwRdo
                   WhAfGFCF5bppETSTojQCrfFPP2oumHKtz"
  }
}
```

Since the proof is embedded in the json structure, the proof must be based in this example on another representation without the proof included. 
What is it in this example? Is it:
```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "id": "http://example.gov/credentials/3732",
  "type": ["VerifiableCredential", "UniversityDegreeCredential"],
  "issuer": "https://example.edu",
  "issuanceDate": "2010-01-01T19:23:24Z",
  "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "degree": {
      "type": "BachelorDegree",
      "name": "Bachelor of Science and Arts"
    }
  }
}
``` 
Or is it the RDF respresentation (which serialisation?)

Suppose it is on the RDF reprsentation then the proof would be valid if I reorder the json to

```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "id": "http://example.gov/credentials/3732",
  
  "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "degree": {
      "type": "BachelorDegree",
      "name": "Bachelor of Science and Arts"
    }
  },
  "type": ["VerifiableCredential", "UniversityDegreeCredential"],
  "issuer": "https://example.edu",
  "issuanceDate": "2010-01-01T19:23:24Z",
}
``` 

Is this also valid for json based representations?

Taking it one step further, suppose I can reorder the json, what would be the effect on adding additional attributes ?

**Comment by brentzundel** [comment]
This confusion is the primary reason for the Securing Verifiable Credentials (SVC) 1.0 work item listed under the [Normative Specifications](https://www.w3.org/2022/06/verifiable-credentials-wg-charter.html#normative) section of the VCWG Charter.

**Comment by bertvannuffelen** [comment]
ok thanks.

**Comment by OR13** [comment]
Related: https://github.com/w3c-ccg/did-method-web/issues/20#issuecomment-1233253411

**Comment by OR13** [comment]
In [credentials v1](https://github.com/w3c/vc-data-model/blob/main/contexts/credentials/v1):

```
 "VerifiableCredential": {
      "@id": "https://www.w3.org/2018/credentials#VerifiableCredential",
        "@context": {
        "@version": 1.1,
        "@protected": true,

        "id": "@id",
        "type": "@type",

        "cred": "https://www.w3.org/2018/credentials#",
        "sec": "https://w3id.org/security#",
...
      "proof": {"@id": "sec:proof", "@type": "@id", "@container": "@graph"},
```

This means that technically the current proof term IRI is:

https://w3id.org/security#proof

Which is controlled by: 

https://github.com/perma-id/w3id.org/tree/master/security

https://github.com/perma-id/w3id.org/blob/master/security/.htaccess#L5

I would expect the "data integrity suites" to define proof... for example:

https://github.com/w3c/vc-data-model/blob/main/contexts/credentials/v1#L235

```
 "proof": {"@id": "https://w3id.org/security#proof", "@type": "@id", "@container": "@graph"}
```

I think data integrity needs a separate context if it's responsible for defining proof semantics... assuming `proof` is ONLY relevant to data integrity... we could decide `proof` is relevant to the core data model, then i would expect credentials/v2 to define it.

**Comment by peacekeeper** [comment]
See Data Integrity specification for more information about these types of proofs: https://w3c.github.io/vc-data-integrity/

**Comment by msporny** [comment]
@bertvannuffelen, we're trying to figure out if your question was answered, or if you would like us to update some specification to answer your question more precisely.

Can you please provide some guidance on whether or not you would like to see a change in a specification, and if so, which specification (and ideally, exactly what text) you'd like to see. If we don't hear from you within the next month or so, we're going to close this issue.

**Comment by bertvannuffelen** [comment]
Hi all,

my question is not on which proofing method is being used but on WHAT the proof signature applies (agnostic to any proofing method).

In the example the payload, containing all information without the proof, is  
```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "id": "http://example.gov/credentials/3732",
  "type": ["VerifiableCredential", "UniversityDegreeCredential"],
  "issuer": "https://example.edu",
  "issuanceDate": "2010-01-01T19:23:24Z",
  "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "degree": {
      "type": "BachelorDegree",
      "name": "Bachelor of Science and Arts"
    }
  }
}
```

Suppose I reorder the payload to

```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "issuer": "https://example.edu",
  "type": ["VerifiableCredential", "UniversityDegreeCredential"],
  
  "issuanceDate": "2010-01-01T19:23:24Z",
  "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "degree": {
      "name": "Bachelor of Science and Arts",
      "type": "BachelorDegree" 
    }
   "id": "http://example.gov/credentials/3732"
  }
}
```

Is then the proof still valid? 

Or if I add new context references:

```
{
  "@context": [
    "https://myimpl.com/context",
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "issuer": "https://example.edu",
  "type": ["VerifiableCredential", "UniversityDegreeCredential"],
  
  "issuanceDate": "2010-01-01T19:23:24Z",
  "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "degree": {
      "name": "Bachelor of Science and Arts",
      "type": "BachelorDegree" 
    }
   "id": "http://example.gov/credentials/3732"
  }
}
```
 
Is then the proof still valid?


In each of the cases I have not touched the information that is contained in the payload. I only reordered the attributes  or I added information.


I am looking for any responses that clearly state:
  - yes, this is valid
  - no, this is invalid because ...

**Comment by dlongley** [comment]
@bertvannuffelen,

The proof is on a canonical representation of the data, as determined by the canonicalization algorithm used by a particular proof suite. Verifiers should choose proof suites that meet their use cases accordingly.

If a proof suite uses a JSON canonicalization algorithm, then any meaningful changes to the JSON will invalidate the signature. Some examples:

* Changing the order in which the JSON keys appear DOES NOT invalidate the signature.
* Adding a new context to the `@context` array DOES invalidate the signature.
* Changing what a context resolves to DOES NOT invalidate the signature.

If a proof suite uses an RDF canonicalization algorithm, then any meaningful changes to the RDF will invalidate the signature. Some examples:

* Changing the order in which the JSON keys appear DOES NOT invalidate the signature.
* Adding a new context to the `@context` array DOES NOT invalidate the signature unless it changes the term mappings.
* Changing what a context resolves to DOES invalidate the signature.

**Comment by bertvannuffelen** [comment]
@dlongley thanks for the explanation. 

These conclusions are extremely valuable to know what to choose. 
I tried to find that information in https://w3c.github.io/vc-data-integrity and https://www.w3.org/TR/vc-data-model/ but it was not there.

As the canonicalization is a critical knowledge to propagate the message through systems, I expect that this is explicitly mentioned in the VC? Which property is used for that? 


Another followup question:

For a VC like this, where in the specification is defined what the payload is?

```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "id": "http://example.gov/credentials/3732",
  "type": ["VerifiableCredential", "UniversityDegreeCredential"],
  "issuer": "https://example.edu",
  "issuanceDate": "2010-01-01T19:23:24Z",
  "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "degree": {
      "type": "BachelorDegree",
      "name": "Bachelor of Science and Arts"
    }
  },
  "proof": {
    "type": "Ed25519Signature2020",
    "created": "2021-11-13T18:19:39Z",
    "verificationMethod": "https://example.edu/issuers/14#key-1",
    "proofPurpose": "assertionMethod",
    "proofValue": "z58DAdFfa9SkqZMVPxAQpic7ndSayn1PzZs6ZjWp1CktyGesjuTSwRdo
                   WhAfGFCF5bppETSTojQCrfFPP2oumHKtz"
  }
}
```

Is it 
```
{
"@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ]
}
```

or 
```
"@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
   "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "degree": {
      "type": "BachelorDegree",
      "name": "Bachelor of Science and Arts"
    }
  }
}
```
or any of the other possible selections?

What is the exact structure on which the proof is applied? Is that somewhere documented?

**Comment by dlongley** [comment]
@bertvannuffelen,

> I tried to find that information in https://w3c.github.io/vc-data-integrity and https://www.w3.org/TR/vc-data-model/ but it was not there.

Yes, this is an oversight that I'm sure will be corrected in due course. We're working on getting the specs to both layer cleanly and be in line with a number of implementations for which there is already interoperability.

> As the canonicalization is a critical knowledge to propagate the message through systems, I expect that this is explicitly mentioned in the VC? Which property is used for that?

It's specific to the Data Integrity mechanism for securing credentials, so this information is carried in the `proof` property of a VC. The suite type determines the canonicalization algorithm used and it is either specified via the `proof.type` property or the `proof.cryptosuite` property (depending on the cryptosuite used).

> For a VC like this, where in the specification is defined what the payload is?

This is touched on in the generic process for [generating a proof](https://w3c.github.io/vc-data-integrity/#generate-proof) and it relies upon the transformation process. The language in this part of the spec is in flux (though what actually happens in interoperable implementations is not) as we work out the best way to express the base process and any layered process from specific cryptosuites on top of it. I'm sure we also need more clarity on the process there and we may have some gaps that have been generated by the recent moving parts between the base spec and specific extending cryptosuite specs.

The short version of any of this is that the the entire "unsecured document" is passed to the transformation process, modulo any existing `proof` field, which enables multiple proofs to be attached to the same document. The signing process covers the whole document and all fields in the new `proof` (to be attached) except for the `proofValue` itself, which holds the output of the cryptographic signature algorithm.

So, for a document that already has a `proof` field, everything except that field (and the existing proofs it contains) will be signed over, including the new proof that will be attached after the signature is generated. It will be added to the set of existing proofs in the `proof` field. If the document did not have a `proof` field (the common case), then what is signed will still be the same but a new `proof` field with a set containing only the new proof will be added.

**Comment by bertvannuffelen** [comment]
@dlongley 

thanks for the explanations, this concludes my questions in this issue. 

I read that you are taking up my questions in your roadmap for improvements. I recommend taking this explanation on the "vc modulo the `proof`" into the specification, as this is a natural reading but not made explicit and thus open for interpretation.
