### ISSUE TITLE
URLs in current editors draft all seem to be invalid

### ISSUE THREAD

**Issue by wip-abramson** [w3c/vc-data-integrity#37]
Specifically:

This version, latest published version and latest editors draft URLs.

Also, the context URL from example 5 does not resolve: https://w3id.org/security/data-integrity/v1. So I am unable to canonicalize.

Think this is likely due to the latest changes from CCG to VCWG?

**Comment by thereisnogabe** [comment]
Seems to be resolving to a Digital Bazaar link now: https://digitalbazaar.github.io/data-integrity-context/contexts/data-integrity-v1.jsonld

Perhaps this should be re-uploaded in this repo? cc: @msporny

**Comment by msporny** [comment]
> Perhaps this should be re-uploaded in this repo? cc: @msporny

Yes, that's the plan once we have the discussion on [streamlining data integrity specs](https://docs.google.com/presentation/d/1hrqozY2EGZ8i8y40abyEuJmIb6hCiRS-37pdj6bhBLY/edit#slide=id.g1482ccb90af_0_90) at W3C TPAC next week. Depending on how that conversation goes, the JSON-LD Contexts could look very different.

**Comment by msporny** [comment]
The WG decided to go the `DataIntegrityProof` route at the last W3C TPAC. We should be pointing here now:

https://w3c.github.io/vc-data-integrity/contexts/data-integrity/v1

... but ideally, it's published here: https://www.w3.org/ns/data-integrity/v1

/cc @iherman

**Comment by msporny** [comment]
@iherman we need to publish this context: 

https://w3c.github.io/vc-data-integrity/contexts/data-integrity/v1 

at this location:

https://www.w3.org/ns/data-integrity/v1

**Comment by iherman** [comment]
I presume when you say "publish", this means creating a redirection to the github file, right? We ***could*** publish a copy any time there is a change, but I would advise against it, at least at the time of the development.

**Comment by msporny** [comment]
> I presume when you say "publish", this means creating a redirection to the github file, right? We _**could**_ publish a copy any time there is a change, but I would advise against it, at least at the time of the development.

Yes, for now, a redirect is fine. Once we hit REC, we will probably want to archive the content in the W3C TR space.

**Comment by iherman** [comment]
https://www.w3.org/ns/data-integrity/v1 is operational now.

**Comment by iherman** [comment]
@brentzundel @Sakurann I believe this issue can be closed (or, at least, flagged as to be closed)

**Comment by msporny** [comment]
Confirmed that all URLs reported by this issue have been fixed and the w3id.org URLs have been updated to point to the W3C locations. Namely, these URLs work now:

https://www.w3.org/ns/data-integrity/v1 resolves now, and is the official location of the JSON-LD Context file for Data Integrity..

The redirects on w3id.org have been updated to the official W3C locations:
https://w3id.org/security/data-integrity -> redirect -> https://www.w3.org/TR/vc-data-integrity/
https://w3id.org/security/data-integrity/v1 -> redirect -> https://www.w3.org/ns/data-integrity/v1

Marking as 7 day pending close.
