### ISSUE TITLE
LD-Proofs v LD-Signatures

### ISSUE THREAD

**Issue by johnptoohey** [w3c/vc-data-integrity#5]
Is there a link to a doc or discussion explaining the difference between proofs and signatures? I'm sure the difference is obvious, but I'm not seeing it. We sign all our JSON-LD docs and use the signature as a proof of ownership and to ensure the integrity of the document. Looking at this spsec, that seems to be its function. Anything that can clarify this would be really helpful. 
Thanks

**Comment by johnptoohey** [comment]
Thanks Manu. I printed out the latest VC Data model paper last night, and that did clear a lot of this up. Like that "evidence" was added to the spec, as we already had that. Also really like the Term of Service addition. Our Verifier partner will really appreciate this :-)

**Comment by dmitrizagidulin** [comment]
Addressed by PR https://github.com/w3c-ccg/ld-proofs/pull/10

**Comment by msporny** [comment]
Noting the above before finishing off this issue... @dmitrizagidulin addressed this via PR #10, closing.
