### ISSUE TITLE
Schema.org namespace typos (hash should be a slash!)

### ISSUE THREAD

**Issue by pmcb55** [w3c/vc-data-integrity#50]
Hi,

I tried to make a simple PR to fix these typos, but it seems I need permission to do so.

Anyway, the fix is trivial - literally just a search-and-replace for `schema.org#` and replacing with `schema.org/` (all 6 occurrences right now are to `https://schema.org#title`).

Cheers,

Pat.

**Comment by msporny** [comment]
Fixed in https://github.com/w3c/vc-data-integrity/pull/54
