### ISSUE TITLE
Explain how proof types are mapped to URLs

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-integrity#60]
The current specification states the following in the definition for `type`:
> The specific <a>proof type</a> used for the cryptographic proof MUST be specified as a string that maps to a URL [[URL]].

The specification does not state how that is performed. When using JSON-LD, that process is performed by associating an `@context` with the message. The process is undefined for JSON (but we could say that the specification defines the mapping).

This issue has been created to make sure we get consensus in the VCWG on the expected path forward and then add the appropriate language into the specification.

**Comment by dlongley** [comment]
I think the process for JSON should be defined as using JSON-LD. To my knowledge, there's no need to invent a new, different, JSON-based mechanism.

**Comment by dlongley** [comment]
To further clarify, simply checking for the presence of a well-known `@context` URL in the JSON should be sufficient to have software understand which mappings are in play.

**Comment by msporny** [comment]
PR #133 has been raised to address this issue. This issue will be closed when the PR is merged.

**Comment by msporny** [comment]
PR #133 has been merged. Closing.
