### ISSUE TITLE
Broken link to CAIP-10Account ID Specification

### ISSUE THREAD

**Issue by orblivion** [w3c/vc-data-integrity#71]
The link in the blockchainAccountId section to the CAIP-10Account ID Specification is currently as such:

```
https://w3c.github.io/vc-data-integrity/vocab/security/%E2%80%9Dhttps://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-10.md%E2%80%9D
```

**Comment by msporny** [comment]
Fixed in https://github.com/w3c/vc-data-integrity/commit/97eccc47547541d34b490d3dea83b9e24c23a223. Closing.
