### ISSUE TITLE
Is the sec entry in vocab/security/vocabulary.jsonld and vocab/security/vocabulary.ttl wrong?

### ISSUE THREAD

**Issue by Daniel-Abrecht** [w3c/vc-data-integrity#72]
`sec` is set to `https://w3id.org/security/v1` here, but shouldn't it be `https://w3id.org/security#`?

https://github.com/w3c/vc-data-integrity/blob/e40bcc8a55eb5da6c9ea2773d269144fe3f18970/vocab/security/vocabulary.jsonld#L3
https://github.com/w3c/vc-data-integrity/blob/e40bcc8a55eb5da6c9ea2773d269144fe3f18970/vocab/security/vocabulary.ttl#L1

Because in the jsonld context in https://w3id.org/security/v1 specifies sec as `https://w3id.org/security#`, so `sec:thing` will be `https://w3id.org/security#thing`, whereas in the files above `sec` is set to `https://w3id.org/security/v1`, so `sec:thing` should end up as `https://w3id.org/security/v1thing` I think, which seams odd to me.

And while I'm at it, in vocabulary.ttl, there are some lines reading `    rdfs:range  ;`, they seam to trip up python rdflib when I try to parse them, so I think these empty ranges should be removed. (They don't add anything there anyway, in turtle, it's always a (subject, predicate, object) tripple, and there are no objects there, only subject & predicate, so there is no tripple)

**Comment by msporny** [comment]
@Daniel-Abrecht wrote:
> sec is set to https://w3id.org/security/v1 here, but shouldn't it be https://w3id.org/security#?

Yes, `sec` is defined incorrectly in the vocabulary.yml file. Thanks for spotting the issue, PR #109 has been raised to fix the issue.

> And while I'm at it, in vocabulary.ttl, there are some lines reading rdfs:range; 

I just re-ran the `yml2vocab` command and it looks like the latest build of that tool doesn't include empty `rdfs:range` declarations.

So, once PR #109 is merged, it looks like we can close this issue.

**Comment by msporny** [comment]
PR #109 has been merged, closing.
