### ISSUE TITLE
domain of publicKeyJWK should be rdf:JSON

### ISSUE THREAD

**Issue by bblfish** [w3c/vc-data-integrity#73]
The json-ld contexts for publicKeyJWK make the value be a rdf:JSON, which cleverly allows the unobtrusive integration of the key as a literal into JSON. But the spec has the range be `rdfs:string`.

So in the [Http Signature protocol](https://github.com/bblfish/authentication-panel/blob/main/proposals/HttpSignature.md) I am developing
I wrote the key in JSON-LD like this

```json
{
"@context": [
    "https://w3id.org/security/v1",
    { "ex": "http://example.org/vocab#" }
  ],
  "id": "#",
  "controller": "/people/alice#i",
  "publicKeyJwk": { 
        "kty":"RSA",
        "e":"AQAB",
        "n" : "hAKYdtoeoy8zcAcR874L8cnZxKzAGwd7v36APp7Pv6Q2jdsPBRrwWEBnez6d0UDKDwGbc6nxfEXAy5mbhgajzrw3MOEt8uA5txSKobBpKDeBLOsdJKFqMGmXCQvEG7YemcxDTRPxAleIAgYYRjTSd_QBwVW9OwNFhekro3RtlinV0a75jfZgkne_YiktSvLG34lw2zqXBDTC5NHROUqGTlML4PlNZS5Ri2U4aCNx2rUPRcKIlE0PuKxI4T-HIaFpv8-rdV6eUgOrB2xeI1dSFFn_nnv5OoZJEIB-VmuKn3DCUcCZSFlQPSXSfBDiUGhwOw76WuSSsf1D4b_vLoJ10w",
        "alg":"PS512",
        "kid":"2021-04-01-laptop"
  }
}
```
Which I worked out to be equivalent to the following turtle

```Turtle
@prefix security: <https://w3id.org/security#> .

</keys/alice#>
     security:controller </people/alice#i> ;
     security:publicKeyJwk """{
            "alg":"PS512",
            "e":"AQAB",
            "kid":"2021-04-01-laptop",
            "kty":"RSA",
            "n":hAKYdtoeoy8zcAcR874L8cnZxKzAGwd7v36APp7Pv6Q2jdsPBRrwWEBnez6d0UDKDwGbc6nxfEXAy5mbhgajzrw3MOEt8uA5txSKobBpKDeBLOsdJKFqMGmXCQvEG7YemcxDTRPxAleIAgYYRjTSd_QBwVW9OwNFhekro3RtlinV0a75jfZgkne_YiktSvLG34lw2zqXBDTC5NHROUqGTlML4PlNZS5Ri2U4aCNx2rUPRcKIlE0PuKxI4T-HIaFpv8-rdV6eUgOrB2xeI1dSFFn_nnv5OoZJEIB-VmuKn3DCUcCZSFlQPSXSfBDiUGhwOw76WuSSsf1D4b_vLoJ10w"
      }"""^^rdf:JSON .
``` 

also if you have `publicKeyJWK` you should also have `privateKeyJWK` so that we don't need to forever be tied to PEMs, which is the only option offered at the moment for private keys.

**Comment by msporny** [comment]
@bblfish wrote:
> The json-ld contexts for publicKeyJWK make the value be a rdf:JSON

Yes, agreed. We'll do this in a future PR.

**Comment by msporny** [comment]
PR #135 has been raised to address this issue. This issue will be closed when that PR is merged.

**Comment by msporny** [comment]
PR #135 has been merged, closing.
