### ISSUE TITLE
Expiration Date

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-integrity#78]
All cryptographic proofs should have an expiration date since no cryptography lasts forever. The current specification includes the `created` property but has no equivalent `expires` property.

**Comment by dlongley** [comment]
The context does provide an `expires` term here: https://github.com/w3c/vc-data-integrity/blob/main/contexts/data-integrity/v1#L23-L26

However, it does look like we don't have examples / text in the spec around its usage.

**Comment by David-Chadwick** [comment]
What is the difference between the created and expires properties of the proof and the validFrom and validTo properties of the VC?

**Comment by Wind4Greg** [comment]
My take is that `created` and `expires` are more associated with the cryptographic properties of the proof and would take into account key material expiration. In addition a VC may contain multiple proof via proof set or proof chain and hence it could be useful to differentiate.

**Comment by David-Chadwick** [comment]
So what does it mean if the proof is not valid (i.e. it is outside its validity period) but the verifiableCredential is valid (i.e. it is inside its validity period)? How can the verifier believe the validity period of the verifiableCredential?

**Comment by msporny** [comment]
> So what does it mean if the proof is not valid (i.e. it is outside its validity period) but the verifiableCredential is valid (i.e. it is inside its validity period)? 

By default, the signature will fail to verify, which means the VC will fail to verify.

> How can the verifier believe the validity period of the verifiableCredential?

Answer above... proof expiration needs to be checked (if it's specified), then validity period for VC. These are business rules, of course, so the verifier could choose to ignore expired proofs.

**Comment by msporny** [comment]
PR #124 has been merged to address this issue. Marking as pending close. @David-Chadwick let us know if you require additional changes.

**Comment by David-Chadwick** [comment]
Where is the text that relates `expires` to validUntil? I could not find anything in the current text that does this.
Note also that `created `should also be related to validFrom.
It makes no sense to me to have different values for these two sets of validity times, given that the VC valid properties are for the VC and not for the unsigned credential.
OTOH if the validFrom and validUntil were properties of the underlying credential then it makes perfect sense for them to be different to the signature `expires` and `created` properties

**Comment by msporny** [comment]
@David-Chadwick wrote:
> OTOH if the validFrom and validUntil were properties of the underlying credential then it makes perfect sense for them to be different to the signature expires and created properties

Yes, correct, that's the expectation. Even in that case, for a VC, you would expect the values to line up (unless there is a very good reason for them not to line up -- like a VC being signed before it becomes valid).

I guess a PR could be raised to note this in the "Relationship to VCs" section of the specification.

**Comment by David-Chadwick** [comment]
Now that we have decided there are three difference concepts: the physical certificate/qualification..., the credential object which is the JSON representation of the latter, and the verifiableCredential which is the credential object with cryptographic proof (internal or external), then I think the VCDM needs updating to state that validFrom and validUntil relate to the validity period of the physical entity, and that expires and created relate to the cryptographic proof.

**Comment by msporny** [comment]
PR #155 has been raised to address the rest of this issue. This issue will be closed when that PR is merged. @David-Chadwick please review PR #155, and if it doesn't work for you -- provide concrete suggestions, so that we can close this issue.

**Comment by David-Chadwick** [comment]
WRT concrete suggestions, the WG needs to come to an agreement on what the VC validity period actually refers to and what the difference is between this and the proof signature validity period. I have my own opinion as stated above. If this becomes the WG's position as well then I will propose concrete text for you.

**Comment by TallTed** [comment]
> [@David-Chadwick] WRT concrete suggestions, the WG needs to come to an agreement on what the VC validity period actually refers to and what the difference is between this and the proof signature validity period. I have my own opinion as stated above. If this becomes the WG's position as well then I will propose concrete text for you.

I submit that such concrete text could go a long way toward the WG adopting it, or being able to provide concrete and focused argument against such adoption, such that we might eventually arrive at a consensus position that includes you along with the rest of the WG.

**Comment by David-Chadwick** [comment]
I have provided a concrete suggestion in #155

**Comment by msporny** [comment]
That change has been applied. 

PR #155 has been merged, closing.
