### ISSUE TITLE
NIST defines data integrity differently

### ISSUE THREAD

**Issue by OR13** [w3c/vc-data-integrity#83]
We define data integrity in the context of RDF information, not "bytes/  data".

<img width="523" alt="Screen Shot 2023-02-16 at 2 50 29 PM" src="https://user-images.githubusercontent.com/8295856/219471914-bbb950fa-8029-40c8-929b-d0bccd79d759.png">

https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63-4.ipd.pdf

**Comment by RieksJ** [comment]
The comment I made on w3c/vc-data-model, issue [#1047](https://github.com/w3c/vc-data-model/issues/1047#issuecomment-1437973501), apply here as well.

**Comment by msporny** [comment]
> We define data integrity in the context of RDF information, not "bytes/ data".

@OR13, what is the concrete action that you would like to be taken based on this issue? 

Given that this is about terminology, which is non-normative, I'm going to mark this as "after CR" and will change that if it seems as if a normative change is being requested on the specification.

**Comment by OR13** [comment]
More elaboration on why it's a favorable property to protect information instead of data.

Perhaps focusing on how order of object members and array items are impacted.

This could probably be rolled into the same PR that elaborates on changing data types using context (the array items issue).

**Comment by OR13** [comment]
@msporny perhaps this is a good example: https://github.com/w3c/vc-data-model/pull/1149#issuecomment-1631719553

Why is it valuable that `iss` with term `https://www.w3.org/ns/credentials/issuer-dependent#iss` be signed and integrity protected, vs `iss` with term `https://www.iana.org/assignments/jose#iss` or `https://www.iana.org/assignments/jwt#iss`

In this section specifically:

https://w3c.github.io/vc-data-integrity/#data-opacity

**Comment by msporny** [comment]
The VCWG has achieved consensus that perfect terminology alignment with other specifications, if there isn't confusion generated around the term, [is a non-goal](https://github.com/w3c/vc-data-model/issues/1301#issuecomment-1932587295). On that basis, it has closed the last remaining terminology alignment request in the VCDM.

Additionally, the assertion in the original issue is not correct, namely:

> We define data integrity in the context of RDF information, not "bytes/ data".

No, the "Data Integrity" specification defines it as "data", which aligns with NIST's definition. We have Data Integrity suites that [secure the data based on non-RDF data structures](https://www.w3.org/TR/vc-di-ecdsa/#ecdsa-jcs-2019), such as JSON.

Based on both of these points, I'm marking this PR as pending close. It will be closed in 7 days unless there are objections.
